<script setup>
import {ref,onMounted,computed} from 'vue'
const c={"title":"care · 健康管理台","sub":"健康档案、随访计划和指标趋势的统一工作台","kicker":"HEALTH / BUSINESS OS","a":"健康档案","b":"随访预约","ar":"members","br":"appointments","nav":["总览","健康档案","随访预约"],"icons":{"总览":"⌂","健康档案":"▦","随访预约":"◷"},"metrics":[["管理人数","2,486","+6.2%"],["本周随访","128","+14"],["达标率","86.4%","+3.8%"],["待提醒","27","需关注"]]}, page=ref('总览'), data=ref({}), input=ref(''), note=ref('')
const primary=computed(()=>data.value[c.ar]||[]), secondary=computed(()=>data.value[c.br]||[])
async function api(p,o){let r=await fetch('/api'+p,o);if(!r.ok)throw Error(await r.text());return r.json()}
async function load(){data.value[c.ar]=await api('/'+c.ar);data.value[c.br]=await api('/'+c.br)}
async function add(){if(!input.value.trim())return;await api('/'+c.ar,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:input.value,status:'待处理',detail:'本机新增演示记录'})});input.value='';note.value='新增成功';await load()}
onMounted(load)
</script>
<template><div class="shell"><aside><div class="brand"><strong>✦</strong><div><b>{{c.title}}</b><small>AI-HUB BUSINESS OS</small></div></div><p class="workspace">业务工作台　⌄</p><nav><button v-for="x in c.nav" :class="{active:page===x}" @click="page=x">{{c.icons[x]}}　{{x}}</button></nav><div class="env">本机演示环境<br><small>Vue 3 · Java 21</small></div></aside><main><header><span>工作台　/　{{page}}</span><div><i></i>服务正常　 <em>A</em> 管理员</div></header><section class="content"><div class="head"><div><small>{{c.kicker}}</small><h1>{{page}}</h1><p>{{c.sub}}</p></div><button class="primary" @click="page=c.a">＋ 新增记录</button></div><template v-if="page==='总览'"><div class="metrics"><article v-for="m in c.metrics"><span>{{m[0]}}</span><b>{{m[1]}}</b><em>{{m[2]}}</em></article></div><div class="grid"><section class="panel chart"><h2>业务趋势</h2><p>最近 7 天核心指标概览</p><div class="bars"><i v-for="n in [44,58,51,73,67,82,76]" :style="{height:n+'%'}"></i></div></section><section class="panel"><h2>快捷操作</h2><p>常用业务入口</p><button v-for="x in [c.a,c.b]" class="quick" @click="page=x">▣　{{x}} <b>→</b></button></section></div><section class="panel"><div class="row"><h2>最近动态</h2><button class="link" @click="page=c.b">查看全部 →</button></div><table><thead><tr><th>事项</th><th>详情</th><th>状态</th><th>信息</th></tr></thead><tbody><tr v-for="r in secondary"><td><b>{{r.name}}</b></td><td>{{r.detail}}</td><td><span class="badge">{{r.status}}</span></td><td>{{r.amount}}</td></tr></tbody></table></section></template><template v-else-if="page===c.a"><section class="panel"><div class="row"><div><h2>{{c.a}} <small>{{primary.length}}</small></h2><p>查看、维护和新增核心业务数据。</p></div><div class="add"><input v-model="input" placeholder="输入名称后新增" @keyup.enter="add"><button class="primary" @click="add">新增</button></div></div><table><thead><tr><th>名称</th><th>详情</th><th>状态</th><th>规模 / 金额</th><th>操作</th></tr></thead><tbody><tr v-for="r in primary"><td><b>{{r.owner||r.name}}</b></td><td>{{r.detail}}</td><td><span class="badge" :class="{warn:r.status==='关注'||r.status==='告警'}">{{r.status}}</span></td><td>{{r.amount}}</td><td><button class="link" @click="note='已打开详情'">查看详情</button></td></tr></tbody></table></section></template><template v-else><section class="panel"><div class="row"><div><h2>{{c.b}} <small>{{secondary.length}}</small></h2><p>跟踪状态、处理进度和业务动态。</p></div><button class="outline" @click="load">刷新数据</button></div><div class="timeline"><article v-for="r in secondary"><i></i><div><b>{{r.name}}</b><p>{{r.detail}}</p><small>{{r.status}} · {{r.amount}}</small></div><button class="link" @click="note='已标记为已读'">处理 →</button></article></div></section></template><p v-if="note" class="note">{{note}}</p></section><footer>© 2026 ai-hub · {{c.title}} <span>Vue 3 + Java 21 · 本机演示</span></footer></main></div></template>