<template>
  <view class="page">
    <view class="nav"><view><text class="brand">LUNE</text><text class="nav-sub">HAIR STUDIO</text></view><text class="nav-title">预约确认</text></view>
    <view class="hero"><view class="hero-icon">✦</view><view><text class="eyebrow">YOUR NEXT LOOK</text><text class="hero-title">把时间留给更好的自己</text><text class="hero-desc">选择服务、设计师与到店时间，预约后即可安心出发。</text></view></view>
    <view class="card process"><view class="card-head"><view><text class="card-title">预约流程</text><text class="card-sub">三步完成你的专属造型</text></view><text class="step-count">01 / 03</text></view><view class="steps"><view class="step active"><text class="step-num">01</text><text class="step-name">选服务</text><text class="step-desc">剪发 · 烫染 · 护理</text></view><view class="line"></view><view class="step"><text class="step-num">02</text><text class="step-name">选设计师</text><text class="step-desc">找到适合你的风格</text></view><view class="line"></view><view class="step"><text class="step-num">03</text><text class="step-name">定时间</text><text class="step-desc">到店免排队</text></view></view></view>
    <view class="card tip"><view class="tip-icon">✓</view><view><text class="tip-title">线上预约，准时到店</text><text class="tip-desc">门店每天 10:00—20:00 营业，建议提前 1 天预约。</text></view></view>
    <button class="primary" @click="go">开始预约 <text>→</text></button>
    <text class="footnote">预约成功后，可在首页输入手机号查看或取消</text>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f5f7fb;color:#162c24;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:6rpx}.nav-sub{display:block;margin-top:4rpx;color:#94a199;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#738078}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#1e6e52,#3f9a73);color:#fff;box-shadow:0 18rpx 45rpx #2f805a30}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:45rpx;color:#d7f6e7}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.7}.hero-title{display:block;margin-top:8rpx;font-size:31rpx;font-weight:800}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.84}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #2238480b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#9aa59f;font-size:18rpx}.step-count{color:#4a8c6d;font-size:18rpx;font-weight:700}.steps{display:flex;align-items:center;margin-top:28rpx}.step{flex:1}.step-num{display:flex;width:48rpx;height:48rpx;align-items:center;justify-content:center;border-radius:16rpx;background:#f0f3f2;color:#718078;font-size:17rpx;font-weight:800}.step.active .step-num{background:#e4f4eb;color:#2e805e}.step-name{display:block;margin-top:13rpx;font-size:20rpx;font-weight:700}.step-desc{display:block;margin-top:6rpx;color:#9aa59f;font-size:16rpx;line-height:1.35}.line{width:24rpx;height:2rpx;margin:0 8rpx;background:#e9eeeb}.tip{display:flex;align-items:center;gap:18rpx}.tip-icon{width:52rpx;height:52rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#e8f7ee;color:#2f8a62;font-size:28rpx;font-weight:800}.tip-title{display:block;font-size:22rpx;font-weight:700}.tip-desc{display:block;margin-top:7rpx;color:#8d9a93;font-size:18rpx;line-height:1.4}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#1f7353;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #287a5730}.primary text{margin-left:8rpx;color:#d7f6e7}.footnote{display:block;margin-top:18rpx;text-align:center;color:#9aa59f;font-size:17rpx}
</style>