<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { request } from '../../services/api'
const services=ref([]), barbers=ref([]), slots=ref([]), bookings=ref([]), serviceId=ref(1), barberId=ref(1), date=ref(''), time=ref('10:00'), customer=ref(''), phone=ref(''), loading=ref(true), message=ref('')
const selectedService=computed(()=>services.value.find(x=>x.id===serviceId.value)||services.value[0]), selectedBarber=computed(()=>barbers.value.find(x=>x.id===barberId.value)||barbers.value[0])
const tomorrow=()=>{const d=new Date(Date.now()+86400000);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function load(){loading.value=true;date.value=tomorrow();try{services.value=await request('/api/services');barbers.value=await request('/api/barbers');await loadSlots();if(phone.value)bookings.value=await request(`/api/bookings?phone=${phone.value}`)}catch(e){message.value=e.message||'服务暂不可用'}finally{loading.value=false}}
async function loadSlots(){try{const data=await request(`/api/slots?barberId=${barberId.value}&date=${date.value}`);slots.value=data.available;if(!slots.value.includes(time.value))time.value=slots.value[0]||''}catch(e){message.value=e.message}}
async function book(){message.value='';try{if(!customer.value||!/^1\d{10}$/.test(phone.value))throw Error('请输入姓名和 11 位手机号');const result=await request('/api/bookings','POST',{serviceId:serviceId.value,barberId:barberId.value,date:date.value,time:time.value,customer:customer.value,phone:phone.value});bookings.value=[result,...bookings.value];message.value='预约成功，店员将按时为你服务';uni.showToast({title:'预约成功',icon:'success'})}catch(e){message.value=e.message||'预约失败'}}
async function cancel(id){try{await request(`/api/bookings/${id}/cancel?phone=${phone.value}`,'POST');bookings.value=await request(`/api/bookings?phone=${phone.value}`);message.value='预约已取消'}catch(e){message.value=e.message}}
onLoad(load)
</script>
<template><view class="page"><view class="hero"><view class="eyebrow">LUNE HAIR STUDIO</view><text class="title">今天，换个更好的自己</text><text class="subtitle">提前预约 · 到店免排队 · 专业设计师</text><view class="hero-pills"><text>营业 10:00—20:00</text><text>附近 1.2km</text></view></view><view v-if="loading" class="notice">正在加载服务...</view><view v-else><view class="section"><view class="section-head"><text class="section-title">选择服务</text><text class="section-tip">按需组合</text></view><scroll-view scroll-x class="service-scroll"><view v-for="s in services" :key="s.id" class="service-card" :class="{active:serviceId===s.id}" @click="serviceId=s.id"><text class="service-icon">{{s.icon}}</text><text class="service-name">{{s.name}}</text><text class="service-desc">{{s.desc}}</text><text class="service-price">¥{{s.price}} <text class="minutes">{{s.minutes}}分钟</text></text></view></scroll-view></view><view class="section"><view class="section-head"><text class="section-title">选择设计师</text><text class="section-tip">专业认证</text></view><view class="barbers"><view v-for="b in barbers" :key="b.id" class="barber" :class="{active:barberId===b.id}" @click="barberId=b.id;loadSlots()"><view class="avatar">{{b.avatar}}</view><text class="barber-name">{{b.name}}</text><text class="barber-level">{{b.level}}</text><text class="barber-specialty">{{b.specialty}}</text></view></view></view><view class="section form-card"><view class="section-head"><text class="section-title">预约时间</text><text class="section-tip">未来 14 天可约</text></view><view class="fields"><picker mode="date" :value="date" :start="tomorrow()" @change="e=>{date=e.detail.value;loadSlots()}"><view class="field"><text>日期</text><text>{{date}}　›</text></view></picker><picker :range="slots" :value="Math.max(0,slots.indexOf(time))" @change="e=>time=slots[e.detail.value]"><view class="field"><text>时段</text><text>{{time||'暂无可约'}}　›</text></view></picker><input v-model="customer" class="input" placeholder="你的姓名"/><input v-model="phone" class="input" type="number" maxlength="11" placeholder="手机号，用于查询预约"/></view><button class="primary" @click="book">确认预约 ¥{{selectedService?.price||0}}</button></view><view class="section"><view class="section-head"><text class="section-title">我的预约</text><text class="section-tip">输入手机号后显示</text></view><view v-if="bookings.length" class="booking" v-for="b in bookings" :key="b.id"><view><text class="booking-title">{{b.serviceName}} · {{b.barberName}}</text><text class="booking-info">{{b.date}} {{b.time}}　¥{{b.price}}</text></view><button class="small" v-if="b.status==='已预约'" @click="cancel(b.id)">取消</button><text v-else class="cancelled">{{b.status}}</text></view><view v-else class="empty">填写手机号后提交预约，即可在这里查看</view></view></view><view v-if="message" class="toast">{{message}}</view></view></template>
<style scoped>.page{min-height:100vh;background:#f7f7f6;padding-bottom:40rpx}.hero{padding:54rpx 36rpx 48rpx;background:linear-gradient(135deg,#233b31,#789382);color:#fff}.eyebrow{font-size:20rpx;letter-spacing:4rpx;opacity:.75}.title{display:block;font-size:48rpx;font-weight:700;margin-top:24rpx}.subtitle{display:block;font-size:25rpx;opacity:.82;margin-top:16rpx}.hero-pills{display:flex;gap:16rpx;margin-top:30rpx}.hero-pills text{background:#ffffff22;border:1rpx solid #ffffff44;border-radius:30rpx;padding:10rpx 18rpx;font-size:21rpx}.section{margin:24rpx 24rpx 0}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18rpx}.section-title{font-size:32rpx;font-weight:700}.section-tip{color:#8c958f;font-size:21rpx}.service-scroll{white-space:nowrap}.service-card{display:inline-flex;vertical-align:top;flex-direction:column;width:250rpx;min-height:274rpx;padding:24rpx;margin-right:18rpx;background:#fff;border:2rpx solid #fff;box-sizing:border-box}.service-card.active{border-color:#365745;background:#eff5f0}.service-icon{font-size:60rpx}.service-name{font-size:28rpx;font-weight:700;margin-top:16rpx}.service-desc{color:#89918c;font-size:20rpx;margin-top:10rpx;white-space:normal}.service-price{color:#bf654a;font-size:30rpx;font-weight:700;margin-top:auto}.minutes{font-weight:400;color:#909994;font-size:19rpx}.barbers{display:flex;gap:16rpx}.barber{background:#fff;padding:20rpx 12rpx;text-align:center;flex:1;border:2rpx solid #fff}.barber.active{border-color:#365745;background:#eff5f0}.avatar{width:76rpx;height:76rpx;border-radius:50%;background:#dce9df;display:flex;align-items:center;justify-content:center;margin:auto;font-size:30rpx;color:#365745}.barber-name{display:block;font-size:25rpx;font-weight:700;margin-top:12rpx}.barber-level,.barber-specialty{display:block;font-size:18rpx;color:#8c958f;margin-top:7rpx}.form-card{background:#fff;padding:24rpx}.fields{background:#f7f8f6;padding:0 20rpx}.field,.input{height:88rpx;display:flex;align-items:center;justify-content:space-between;border-bottom:1rpx solid #e9ece9;font-size:24rpx;color:#66736a}.input{width:100%;box-sizing:border-box}.primary{margin-top:24rpx;background:#365745;color:#fff;border:0;height:82rpx;line-height:82rpx;font-size:28rpx}.booking{background:#fff;padding:22rpx;display:flex;justify-content:space-between;align-items:center;border-bottom:1rpx solid #f0f1ef}.booking-title,.booking-info{display:block}.booking-title{font-size:25rpx;font-weight:700}.booking-info{font-size:20rpx;color:#8a948d;margin-top:10rpx}.small{font-size:20rpx;background:#fff;border:1rpx solid #bbc5bd;padding:4rpx 14rpx}.cancelled{font-size:20rpx;color:#9aa39d}.empty,.notice{padding:34rpx;text-align:center;color:#969f99;background:#fff}.toast{position:fixed;bottom:30rpx;left:24rpx;right:24rpx;padding:22rpx;background:#263a30;color:#fff;text-align:center;font-size:23rpx}</style>
