<template>
  <view class="page">
    <view class="nav"><view><text class="brand">食刻</text><text class="nav-sub">TABLE SERVICE</text></view><text class="nav-title">订单</text></view>
    <view class="hero"><view class="hero-icon">⌁</view><view><text class="eyebrow">TABLE STATUS</text><text class="hero-title">这一桌的美味，正在路上</text><text class="hero-desc">下单后可在点餐页查看订单号、菜品、金额和制作进度。</text></view></view>
    <view class="card"><view class="card-head"><view><text class="card-title">订单状态</text><text class="card-sub">后厨进度实时同步</text></view><text class="badge">本桌订单</text></view><view class="timeline"><view class="timeline-item active"><text class="dot">✓</text><view><text class="timeline-title">提交订单</text><text class="timeline-desc">菜品已送达后厨</text></view></view><view class="timeline-line"></view><view class="timeline-item"><text class="dot">02</text><view><text class="timeline-title">制作中</text><text class="timeline-desc">厨师正在准备你的餐点</text></view></view><view class="timeline-line"></view><view class="timeline-item"><text class="dot">03</text><view><text class="timeline-title">待取餐 / 上桌</text><text class="timeline-desc">完成后会第一时间提醒</text></view></view></view></view>
    <view class="card tip-card"><view class="note-icon">i</view><view><text class="note-title">想再加点？</text><text class="note-desc">直接返回点餐页继续选择，新增菜品会合并到本桌订单。</text></view></view>
    <button class="primary" @click="go">返回点餐 <text>→</text></button>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f6f7fb;color:#291c1a;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:5rpx}.nav-sub{display:block;margin-top:4rpx;color:#aa9a96;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#8f7c77}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#93372f,#dd7852);color:#fff;box-shadow:0 18rpx 45rpx #ba594030}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:42rpx;color:#ffe8de}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.72}.hero-title{display:block;margin-top:8rpx;font-size:30rpx;font-weight:800;line-height:1.35}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.85}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #55352e0b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#a4948f;font-size:18rpx}.badge{padding:8rpx 14rpx;border-radius:20rpx;background:#fff1eb;color:#c8583e;font-size:16rpx}.timeline{margin-top:26rpx}.timeline-item{display:flex;align-items:center;gap:16rpx}.dot{width:50rpx;height:50rpx;display:flex;align-items:center;justify-content:center;border-radius:17rpx;background:#f0f2f3;color:#89918f;font-size:17rpx;font-weight:800}.timeline-item.active .dot{background:#fff0eb;color:#c8583e}.timeline-title{display:block;font-size:21rpx;font-weight:700}.timeline-desc{display:block;margin-top:7rpx;color:#998d89;font-size:18rpx}.timeline-line{height:28rpx;width:2rpx;margin-left:24rpx;background:#eee7e4}.tip-card{display:flex;align-items:center;gap:16rpx}.note-icon{width:52rpx;height:52rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#fff5e9;color:#c27c3d;font-size:25rpx;font-weight:800}.note-title{display:block;font-size:21rpx;font-weight:700}.note-desc{display:block;margin-top:7rpx;color:#998d89;font-size:18rpx;line-height:1.4}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#a84235;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #ad4b3a30}.primary text{margin-left:8rpx;color:#ffe1d7}
</style>