package dev.aihub.school;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class SchoolApplication { public static void main(String[] args){SpringApplication.run(SchoolApplication.class,args);} }
@RestController @RequestMapping("/api") class SchoolController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 SchoolController(){ metrics.put("primary","students"); metrics.put("title","campus · 学校教务台"); metrics.put("在校学生","3,862");metrics.put("今日课程","186");metrics.put("出勤率","96.8%");metrics.put("待审批","24"); data.computeIfAbsent("students",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","高一（3）班","detail","班主任：林老师","status","正常","amount","48 人")));data.computeIfAbsent("students",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","初二（1）班","detail","班主任：周老师","status","关注","amount","46 人")));data.computeIfAbsent("students",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","六年级（2）班","detail","班主任：陈老师","status","正常","amount","42 人")));data.computeIfAbsent("courses",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","课程签到","detail","高一数学 · 第 2 节","status","已完成","amount","48/48")));data.computeIfAbsent("courses",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","请假申请","detail","李同学 · 病假","status","待审批","amount","班主任")));data.computeIfAbsent("courses",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","家校通知","detail","秋季社会实践","status","已发送","amount","3,862 人"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}