<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import './style.css'

const nav = [{ key:'overview',label:'研究总览',icon:'◈' },{key:'experiments',label:'实验记录',icon:'▤'},{key:'samples',label:'样本台账',icon:'⬡'},{key:'templates',label:'学科模板',icon:'▦'}]
const active=ref('overview'), experiments=ref([]), samples=ref([]), templates=ref([])
const search=ref(''), discipline=ref('全部学科'), status=ref('全部状态'), loading=ref(true), error=ref(''), notice=ref('')
const drawer=ref(''), formError=ref(''), editing=ref(null), detail=ref(null), history=ref([]), selectedRevision=ref(null)
const form=reactive({})
const today=()=>{ const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }
const disciplines=computed(()=>templates.value.map(x=>x.discipline))
const filtered=computed(()=>experiments.value.filter(e=>(discipline.value==='全部学科'||e.discipline===discipline.value)&&(status.value==='全部状态'||e.status===status.value)&&`${e.title} ${e.researcher} ${e.tags} ${e.hypothesis}`.toLowerCase().includes(search.value.toLowerCase().trim())))
const sampleName=id=>samples.value.find(s=>s.id===id)?.name||'未关联样本'
const latest=computed(()=>[...experiments.value].sort((a,b)=>b.id-a.id).slice(0,4))
const counts=computed(()=>({total:experiments.value.length,active:experiments.value.filter(e=>e.status==='进行中').length,done:experiments.value.filter(e=>e.status==='已完成').length,samples:samples.value.length}))
const disciplineColor=d=>({'生命科学':'violet','化学':'orange','物理':'blue','材料科学':'teal','环境科学':'green','地球科学':'amber','天文学':'indigo','计算科学':'pink'})[d]||'blue'
async function api(path,options){
 const res=await fetch(`/api/${path}`,{headers:{'Content-Type':'application/json'},...options})
 if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.detail||data.message||`请求失败（${res.status}）`)}
 return res.status===204?null:res.json()
}
async function load(){loading.value=true;try{[experiments.value,samples.value,templates.value]=await Promise.all([api('experiments'),api('samples'),api('templates')]);error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
function go(key){active.value=key;search.value='';discipline.value='全部学科';status.value='全部状态';detail.value=null;drawer.value='';notice.value=''}
function openExperiment(row=null,tpl=null){Object.keys(form).forEach(k=>delete form[k]);editing.value=row?.id||null;Object.assign(form,{title:row?.title||'',discipline:row?.discipline||tpl?.discipline||templates.value[0]?.discipline||'生命科学',researcher:row?.researcher||'',date:row?.date||today(),status:row?.status||'计划中',hypothesis:row?.hypothesis||'',protocol:row?.protocol||'',sampleId:row?.sampleId||'',observations:row?.observations||'',results:row?.results||'',conclusion:row?.conclusion||'',dataLocation:row?.dataLocation||'',tags:row?.tags||''});drawer.value='experiment';formError.value='';error.value=''}
function openSample(row=null){Object.keys(form).forEach(k=>delete form[k]);editing.value=row?.id||null;Object.assign(form,{code:row?.code||'',name:row?.name||'',type:row?.type||'',source:row?.source||'',storage:row?.storage||'',notes:row?.notes||''});drawer.value='sample';formError.value='';error.value=''}
async function save(){
 try{
  const type=drawer.value;const route=type==='experiment'?'experiments':'samples';const data=type==='experiment'?{...form,sampleId:form.sampleId?Number(form.sampleId):null}:{...form}
  const item=await api(`${route}${editing.value?'/'+editing.value:''}`,{method:editing.value?'PUT':'POST',body:JSON.stringify(data)})
  const items=await api(route);if(type==='experiment')experiments.value=items;else samples.value=items
  drawer.value='';error.value='';notice.value=editing.value?'修订已保存':'记录已创建'
  if(type==='experiment'&&detail.value?.id===item.id)await showDetail(item)
 }catch(e){formError.value=e.message}
}
async function showDetail(row){try{detail.value=await api(`experiments/${row.id}`);history.value=await api(`experiments/${row.id}/history`);selectedRevision.value=history.value[0]||null;error.value=''}catch(e){error.value=e.message}}
async function archive(row){if(!confirm('归档后不可再修改，确定归档？'))return;try{await api(`experiments/${row.id}`,{method:'PUT',body:JSON.stringify({...row,status:'已归档'})});experiments.value=await api('experiments');detail.value=null;notice.value='实验已归档';error.value=''}catch(e){error.value=e.message}}
async function removeSample(row){if(!confirm(`删除样本 ${row.code}？已关联实验的样本不能删除。`))return;try{await api(`samples/${row.id}`,{method:'DELETE'});samples.value=await api('samples');notice.value='样本已删除';error.value=''}catch(e){error.value=e.message}}
async function download(){try{const res=await fetch('/api/export');if(!res.ok)throw new Error('导出失败');const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`labbook-${today()}.json`;a.click();URL.revokeObjectURL(url);notice.value='已导出 JSON（包含修订历史）'}catch(e){error.value=e.message}}
onMounted(load)
</script>

<template>
<div class="shell">
 <aside class="sidebar"><div class="brand"><span class="brand-icon">✳</span><div><strong>LABNOTE</strong><small>AI-HUB · RESEARCH</small></div></div>
  <div class="workspace-label">科研工作区 <span>LOCAL</span></div>
  <nav aria-label="主导航"><button v-for="item in nav" :key="item.key" :class="{active:active===item.key}" @click="go(item.key)"><span class="nav-icon">{{item.icon}}</span>{{item.label}}<span v-if="item.key==='experiments'" class="nav-count">{{counts.total}}</span></button></nav>
  <div class="sidebar-spacer"></div><div class="sidebar-note"><span class="sidebar-note-icon">◎</span><strong>数据保留在本机</strong><p>实验记录与修订历史保存为 JSON。请定期导出备份。</p></div><div class="sidebar-footer"><span class="live-dot"></span> 单用户演示环境<br><small>Java 21 · Vue 3</small></div>
 </aside>
 <div class="content"><header class="topbar"><div class="breadcrumb">实验空间 <span>/</span> {{nav.find(x=>x.key===active)?.label}}</div><div class="top-actions"><span class="local-badge"><i></i> 本机运行</span><button class="avatar" aria-label="用户">研</button></div></header>
  <main><div v-if="error" class="alert" role="alert">{{error}} <button @click="error=''">×</button></div><div v-if="notice" class="notice">✓ {{notice}} <button @click="notice=''">×</button></div>
   <div v-if="loading" class="empty loading">正在读取实验记录…</div>
   <template v-else-if="active==='overview'">
    <div class="page-head"><div><div class="eyebrow">RESEARCH WORKSPACE / OVERVIEW</div><h1>让每一次探索，都有迹可循<span class="dot">.</span></h1><p>从假设到结论，统一记录跨学科实验与样本。</p></div><button class="primary" @click="openExperiment()">＋ 新建实验记录</button></div>
    <section class="hero"><div><div class="hero-kicker"><span class="hero-pulse"></span> YOUR RESEARCH, ORGANIZED</div><h2>灵感始于提问，<br>发现值得被完整记录。</h2><p>结构化过程 · 样本关联 · 每次修订留痕</p><button @click="go('templates')">探索学科模板 <span>↗</span></button></div><div class="hero-visual"><div class="ring ring-one"></div><div class="ring ring-two"></div><div class="atom">✳</div><span class="coordinate top">EXP / 001</span><span class="coordinate bottom">RESEARCH IN PROGRESS</span></div></section>
    <div class="metric-grid"><article><span>实验总数 <b>01</b></span><strong>{{counts.total.toString().padStart(2,'0')}}</strong><small>所有学科记录</small></article><article><span>进行中 <b>02</b></span><strong>{{counts.active.toString().padStart(2,'0')}}</strong><small>持续跟踪的实验</small></article><article><span>已完成 <b>03</b></span><strong>{{counts.done.toString().padStart(2,'0')}}</strong><small>已形成结论</small></article><article><span>样本总量 <b>04</b></span><strong>{{counts.samples.toString().padStart(2,'0')}}</strong><small>可关联的样本档案</small></article></div>
    <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><span class="eyebrow">RECENT EXPERIMENTS</span><h3>近期实验</h3></div><button class="inline-btn" @click="go('experiments')">查看全部 ↗</button></div><div v-if="!latest.length" class="empty">还没有实验，点击右上角创建。</div><button v-for="row in latest" :key="row.id" class="recent-row" @click="showDetail(row)"><span class="discipline-symbol" :class="disciplineColor(row.discipline)">✳</span><span class="recent-main"><strong>{{row.title}}</strong><small>{{row.discipline}} · {{row.researcher}} · {{row.date}}</small></span><span class="status-pill" :class="row.status">{{row.status}}</span><span class="arrow">↗</span></button></section>
     <section class="panel insight-panel"><div class="panel-head"><div><span class="eyebrow">RESEARCH TOOLS</span><h3>快捷开始</h3></div></div><button class="shortcut" @click="go('templates')"><span class="shortcut-icon">▦</span><span><strong>选择学科模板</strong><small>覆盖 8 个研究方向</small></span><b>→</b></button><button class="shortcut" @click="openSample()"><span class="shortcut-icon aqua">⬡</span><span><strong>登记研究样本</strong><small>关联来源与存放位置</small></span><b>→</b></button><button class="shortcut" @click="download"><span class="shortcut-icon sand">⇩</span><span><strong>导出完整数据</strong><small>实验、样本与修订历史</small></span><b>→</b></button></section></div>
   </template>
   <template v-else-if="active==='experiments'"><div class="page-head"><div><div class="eyebrow">LABNOTE / EXPERIMENTS</div><h1>实验记录<span class="dot">.</span></h1><p>追踪方法、观察、结果与每一次修订。</p></div><button class="primary" @click="openExperiment()">＋ 新建实验</button></div>
    <section class="panel list-panel"><div class="panel-head"><div><span class="eyebrow">EXPERIMENT LIBRARY</span><h3>全部实验 <small>{{filtered.length}} 项</small></h3></div><button class="export" @click="download">⇩ 导出数据</button></div><div class="filters"><input v-model="search" type="search" placeholder="搜索标题、研究者或标签…" aria-label="搜索实验"><select v-model="discipline" aria-label="筛选学科"><option>全部学科</option><option v-for="d in disciplines" :key="d">{{d}}</option></select><select v-model="status" aria-label="筛选状态"><option>全部状态</option><option>计划中</option><option>进行中</option><option>已完成</option><option>已归档</option></select></div><div v-if="!filtered.length" class="empty">没有匹配的实验记录。</div><div v-else class="table-wrap"><table><thead><tr><th>实验 / 编号</th><th>学科</th><th>研究者</th><th>实验日期</th><th>状态</th><th>修订</th><th></th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id" @click="showDetail(row)"><td><strong>{{row.title}}</strong><small>EXP-{{String(row.id).padStart(4,'0')}} · {{row.tags||'未设标签'}}</small></td><td><span class="discipline-chip" :class="disciplineColor(row.discipline)">{{row.discipline}}</span></td><td>{{row.researcher}}</td><td>{{row.date}}</td><td><span class="status-pill" :class="row.status">{{row.status}}</span></td><td>v{{row.revision}}</td><td><button class="row-link" @click.stop="showDetail(row)">查看 ↗</button></td></tr></tbody></table></div></section>
   </template>
   <template v-else-if="active==='samples'"><div class="page-head"><div><div class="eyebrow">LABNOTE / SAMPLE REGISTRY</div><h1>样本台账<span class="dot">.</span></h1><p>记录来源、编号与存放信息，让实验结果可追溯。</p></div><button class="primary" @click="openSample()">＋ 登记样本</button></div><section class="panel list-panel"><div class="panel-head"><div><span class="eyebrow">SAMPLE INVENTORY</span><h3>全部样本 <small>{{samples.length}} 项</small></h3></div><span class="hint">被实验引用的样本不可删除</span></div><div v-if="!samples.length" class="empty">暂无样本，点击右上角登记。</div><div v-else class="table-wrap"><table><thead><tr><th>样本名称 / 编号</th><th>类型</th><th>来源</th><th>存放位置</th><th>关联实验</th><th>操作</th></tr></thead><tbody><tr v-for="row in samples" :key="row.id"><td><strong>{{row.name}}</strong><small>{{row.code}}</small></td><td>{{row.type}}</td><td>{{row.source||'—'}}</td><td>{{row.storage||'—'}}</td><td>{{experiments.filter(e=>e.sampleId===row.id).length}} 项</td><td><button class="row-link" @click="openSample(row)">编辑</button><button class="row-link danger" @click="removeSample(row)">删除</button></td></tr></tbody></table></div></section>
   </template>
   <template v-else><div class="page-head"><div><div class="eyebrow">LABNOTE / DISCIPLINE TEMPLATES</div><h1>从你的研究领域出发<span class="dot">.</span></h1><p>八个方向的结构化起点；具体实验方法仍由研究者与机构 SOP 决定。</p></div></div><div class="template-grid"><article v-for="(tpl,index) in templates" :key="tpl.discipline" class="template-card"><div class="template-top"><span class="template-icon" :class="disciplineColor(tpl.discipline)">✳</span><span class="template-index">{{String(index+1).padStart(2,'0')}} / 08</span></div><div class="eyebrow">{{tpl.discipline.toUpperCase()}}</div><h3>{{tpl.name}}</h3><p>{{tpl.hint}}</p><button @click="openExperiment(null,tpl)">使用此模板 <span>↗</span></button></article></div></template>
   <footer>LABNOTE · AI-HUB <span>本机单用户科研记录演示，非受监管电子实验记录系统</span></footer>
  </main>
 </div>
 <div v-if="detail" class="overlay" @click.self="detail=null"><aside class="detail-drawer"><div class="drawer-top"><div><span class="eyebrow">EXPERIMENT / EXP-{{String(detail.id).padStart(4,'0')}}</span><h2>{{detail.title}}</h2></div><button class="close" aria-label="关闭详情" @click="detail=null">×</button></div><div class="detail-meta"><span class="discipline-chip" :class="disciplineColor(detail.discipline)">{{detail.discipline}}</span><span class="status-pill" :class="detail.status">{{detail.status}}</span><span>版本 v{{detail.revision}}</span></div><div class="detail-actions"><button v-if="detail.status!=='已归档'" class="primary" @click="openExperiment(detail)">编辑并生成修订</button><button v-if="detail.status!=='已归档'" class="outline" @click="archive(detail)">归档</button></div><div class="detail-section"><h3>实验信息</h3><dl><div><dt>研究者</dt><dd>{{detail.researcher}}</dd></div><div><dt>日期</dt><dd>{{detail.date}}</dd></div><div><dt>关联样本</dt><dd>{{sampleName(detail.sampleId)}}</dd></div><div><dt>标签</dt><dd>{{detail.tags||'—'}}</dd></div><div><dt>原始数据位置</dt><dd>{{detail.dataLocation||'—'}}</dd></div></dl></div><div v-for="[label,key] in [['研究假设','hypothesis'],['实验方法','protocol'],['过程观察','observations'],['结果','results'],['结论','conclusion']]" :key="key" class="detail-section"><h3>{{label}}</h3><p class="detail-text">{{detail[key]||'尚未记录'}}</p></div><div class="detail-section"><h3>修订历史 <small>{{history.length}} 次</small></h3><button v-for="r in history" :key="r.revision" class="history-row" :class="{chosen:selectedRevision?.revision===r.revision}" @click="selectedRevision=r"><b>v{{r.revision}}</b><span>{{r.operation}}<small>{{r.recordedAt.replace('T',' ').slice(0,19)}}</small></span><i>→</i></button><div v-if="selectedRevision" class="revision-preview"><strong>v{{selectedRevision.revision}} 快照</strong><p>{{selectedRevision.snapshot.title}} · {{selectedRevision.snapshot.status}}</p><small>结果：{{selectedRevision.snapshot.results||'尚未记录'}}</small></div></div></aside></div>
 <div v-if="drawer" class="overlay editor-overlay" @click.self="drawer=''" ><aside class="editor-drawer"><div class="drawer-top"><div><span class="eyebrow">{{drawer==='experiment'?'EXPERIMENT EDITOR':'SAMPLE EDITOR'}}</span><h2>{{editing?'编辑':'新建'}}{{drawer==='experiment'?'实验记录':'样本档案'}}</h2></div><button class="close" aria-label="关闭编辑" @click="drawer=''">×</button></div><p class="form-intro">{{drawer==='experiment'?'保存修订后将自动生成版本快照。归档后不可再修改。':'使用唯一编号登记样本，便于后续关联实验。'}}</p><div v-if="formError" class="alert form-alert" role="alert">{{formError}} <button @click="formError=''">×</button></div><form @submit.prevent="save">
  <template v-if="drawer==='experiment'"><label>实验标题 *<input v-model="form.title" required maxlength="120" placeholder="例如：涂层性能对比"></label><div class="form-two"><label>研究学科 *<select v-model="form.discipline" required><option v-for="d in disciplines" :key="d">{{d}}</option></select></label><label>实验日期 *<input v-model="form.date" type="date" required></label></div><div class="form-two"><label>研究者 *<input v-model="form.researcher" required maxlength="80" placeholder="研究者姓名"></label><label>状态 *<select v-model="form.status"><option>计划中</option><option>进行中</option><option>已完成</option><option>已归档</option></select></label></div><label>关联样本<select v-model="form.sampleId"><option value="">不关联</option><option v-for="s in samples" :key="s.id" :value="s.id">{{s.code}} · {{s.name}}</option></select></label><label>研究假设<textarea v-model="form.hypothesis" maxlength="2000" rows="2" placeholder="想验证的问题或假设"></textarea></label><label>实验方法 / 记录依据 *<textarea v-model="form.protocol" maxlength="4000" rows="3" required placeholder="记录实际使用的方法、条件与机构 SOP 引用"></textarea></label><label>过程观察<textarea v-model="form.observations" maxlength="4000" rows="3" placeholder="按时间记录实际观察"></textarea></label><label>结果{{['已完成','已归档'].includes(form.status)?' *':''}}<textarea v-model="form.results" maxlength="4000" rows="3" :required="['已完成','已归档'].includes(form.status)" placeholder="测量结果及单位；原始文件另存"></textarea></label><label>结论{{['已完成','已归档'].includes(form.status)?' *':''}}<textarea v-model="form.conclusion" maxlength="4000" rows="3" :required="['已完成','已归档'].includes(form.status)" placeholder="结论、偏差与下一步"></textarea></label><div class="form-two"><label>原始数据位置<input v-model="form.dataLocation" maxlength="500" placeholder="文件路径 / 数据集标识"></label><label>标签<input v-model="form.tags" maxlength="200" placeholder="逗号分隔"></label></div></template>
  <template v-else><div class="form-two"><label>样本编号 *<input v-model="form.code" required maxlength="60" placeholder="S-001"></label><label>样本类型 *<input v-model="form.type" required maxlength="80" placeholder="环境样本"></label></div><label>样本名称 *<input v-model="form.name" required maxlength="120" placeholder="样本名称"></label><label>来源<input v-model="form.source" maxlength="300" placeholder="采样地点 / 来源"></label><label>存放位置<input v-model="form.storage" maxlength="300" placeholder="保存条件与位置"></label><label>备注<textarea v-model="form.notes" maxlength="500" rows="3"></textarea></label></template>
  <div class="form-actions"><button type="button" class="outline" @click="drawer=''">取消</button><button type="submit" class="primary">保存{{editing?'修订':'记录'}}</button></div></form></aside></div>
</div>
</template>
