package dev.aihub.finance;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class FinanceApplication { public static void main(String[] args){SpringApplication.run(FinanceApplication.class,args);} }
@RestController @RequestMapping("/api") class FinanceController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 FinanceController(){ metrics.put("primary","accounts"); metrics.put("title","fin · 金融经营台"); metrics.put("资产总额","¥ 8,420,600");metrics.put("本月收入","¥ 1,286,400");metrics.put("待处理事项","16");metrics.put("风险提示","3"); data.computeIfAbsent("accounts",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","星河科技","detail","经营账户 · 6222","status","正常","amount","¥ 3,260,000")));data.computeIfAbsent("accounts",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","森野生活","detail","结算账户 · 1088","status","正常","amount","¥ 1,180,500")));data.computeIfAbsent("accounts",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","远航教育","detail","备用金账户 · 7721","status","关注","amount","¥ 268,900")));data.computeIfAbsent("transactions",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","回款入账","detail","星河科技 · 服务款","status","已入账","amount","+¥ 280,000")));data.computeIfAbsent("transactions",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","供应商付款","detail","云服务采购","status","已完成","amount","-¥ 62,400")));data.computeIfAbsent("transactions",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","工资发放","detail","9 月薪酬批次","status","待复核","amount","-¥ 416,800"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}