<script setup>
import { ref, computed, onMounted } from 'vue'
const requests = ref([]), stats = ref({ total: 0, draft: 0, pending: 0, approved: 0 })
const filter = ref('全部申请'), selected = ref(null), modal = ref(false), busy = ref(false), error = ref(''), reviewNote = ref('')
const form = ref({ type: '请假', title: '', applicant: '', detail: '', amount: 0 })
const tabs = ['全部申请', '待我审批', '我的草稿', '已处理']
const visible = computed(() => requests.value.filter(r => filter.value === '全部申请' || filter.value === '待我审批' && r.status === '待审批' || filter.value === '我的草稿' && r.status === '草稿' || filter.value === '已处理' && ['已通过', '已驳回'].includes(r.status)))
async function api(path, options) { const response = await fetch('/api' + path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error(`操作失败（HTTP ${response.status}），请检查输入或当前状态`); return response.json() }
async function load() { try { error.value = ''; [requests.value, stats.value] = await Promise.all([api('/requests'), api('/stats')]); if (selected.value) selected.value = requests.value.find(r => r.id === selected.value.id) || null } catch (e) { error.value = e.message } }
async function act(work) { busy.value = true; error.value = ''; try { await work(); await load() } catch (e) { error.value = e.message } finally { busy.value = false } }
async function create() { await act(async () => { await api('/requests', { method: 'POST', body: JSON.stringify({ ...form.value, amount: form.value.type === '请假' ? 0 : Number(form.value.amount) }) }); form.value = { type: '请假', title: '', applicant: '', detail: '', amount: 0 }; modal.value = false; filter.value = '我的草稿' }) }
async function submit(r) { await act(() => api(`/requests/${r.id}/submit`, { method: 'POST' })) }
async function review(r, decision) { await act(async () => { await api(`/requests/${r.id}/review`, { method: 'POST', body: JSON.stringify({ decision, note: reviewNote.value }) }); reviewNote.value = '' }) }
onMounted(load)
</script>
<template>
<div class="app-shell">
  <aside class="sidebar"><div class="brand"><span class="brand-mark">≋</span><div><strong>flow<span>.</span></strong><small>WORK SMARTER</small></div></div><div class="workspace"><span class="workspace-icon">F</span><div><b>远山创意工作室</b><small>协作空间</small></div><span>⌄</span></div><div class="nav-label">工作台</div><button class="nav-item active" @click="filter = '全部申请'"><span>▦</span> 审批工作台</button><div class="nav-label secondary-label">申请管理</div><button v-for="item in tabs" :key="item" :class="['nav-item', { active: filter === item && item !== '全部申请' }]" @click="filter = item"><span>{{ { '全部申请': '◫', '待我审批': '◷', '我的草稿': '▤', '已处理': '✓' }[item] }}</span>{{ item }} <em v-if="item === '待我审批'">{{ stats.pending }}</em></button><div class="sidebar-bottom"><span class="avatar">知</span><div><b>知夏</b><small>演示用户 · 无真实鉴权</small></div><span>···</span></div></aside>
  <main class="main"><header class="topbar"><div>工作台 <span>/</span> 审批中心</div><div class="top-actions"><span class="live-dot"></span> 数据仅存于内存 <span class="avatar small">知</span></div></header><div class="content"><div v-if="error" class="alert">{{ error }} <button @click="load">重试</button><button @click="error = ''">×</button></div><div class="page-heading"><div><div class="eyebrow">SEPTEMBER 2026 · TEAM WORKSPACE</div><h1>让每一个流程，都有清晰的去向<span>✳</span></h1><p>从发起到决策，让团队协作更轻盈、更有序。</p></div><button class="primary" @click="modal = true">＋ 发起申请</button></div><div class="stat-grid"><div class="stat-card"><div class="stat-top"><span>全部申请</span><i>▤</i></div><strong>{{ stats.total }}<small> 条</small></strong><p>工作空间中的所有记录</p></div><div class="stat-card"><div class="stat-top"><span>待审批</span><i>◷</i></div><strong>{{ stats.pending }}<small> 条</small></strong><p>等待做出决定</p></div><div class="stat-card"><div class="stat-top"><span>已通过</span><i>✓</i></div><strong>{{ stats.approved }}<small> 条</small></strong><p>已完成审批流程</p></div><div class="stat-card"><div class="stat-top"><span>草稿箱</span><i>✎</i></div><strong>{{ stats.draft }}<small> 条</small></strong><p>尚未提交的申请</p></div></div><div class="overview"><div class="overview-icon">✦</div><div><strong>把精力留给真正重要的事</strong><p>请假与报销申请，统一管理。新申请先存为草稿，确认后再提交审批。</p></div><button @click="modal = true">创建新申请 ↗</button></div><div class="panel"><div class="panel-head"><div><div class="eyebrow">APPLICATIONS</div><h2>申请列表 <em>{{ visible.length }}</em></h2></div><span>点击申请查看详情与处理操作</span></div><div class="tab-row"><button v-for="item in tabs" :key="item" :class="{ chosen: filter === item }" @click="filter = item">{{ item }}<span v-if="item === '待我审批'">{{ stats.pending }}</span></button></div><div class="table-wrap"><table><thead><tr><th>申请事项</th><th>类型</th><th>申请人</th><th>提交日期</th><th>金额</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="r in visible" :key="r.id" @click="selected = r"><td><div class="title-cell"><span :class="['type-icon', r.type === '报销' ? 'orange' : '']">{{ r.type === '报销' ? '↗' : '☼' }}</span><div><b>{{ r.title }}</b><small>#REQ-{{ String(r.id).padStart(4, '0') }}</small></div></div></td><td>{{ r.type }}</td><td><span class="person"><span class="mini-avatar">{{ r.applicant[0] }}</span>{{ r.applicant }}</span></td><td>{{ r.createdAt }}</td><td>{{ r.type === '报销' ? '¥' + r.amount.toLocaleString() : '—' }}</td><td><span :class="['badge', r.status === '已通过' ? 'success' : r.status === '待审批' ? 'waiting' : r.status === '已驳回' ? 'rejected' : 'draft']"><span>●</span>{{ r.status }}</span></td><td class="arrow">↗</td></tr></tbody></table><div v-if="!visible.length" class="empty">这里还没有申请。试试发起一条新申请吧。</div></div></div><footer>flow · 轻量审批演示 <span>Vue 3 × Java 21</span></footer></div></main>
  <div v-if="selected" class="overlay" @click.self="selected = null"><div class="drawer"><button class="close" @click="selected = null">×</button><div class="eyebrow">APPLICATION / #REQ-{{ String(selected.id).padStart(4, '0') }}</div><h2>{{ selected.title }}</h2><span :class="['badge', selected.status === '已通过' ? 'success' : selected.status === '待审批' ? 'waiting' : 'draft']">{{ selected.status }}</span><div class="detail-grid"><div><small>申请类型</small><strong>{{ selected.type }}</strong></div><div><small>申请人</small><strong>{{ selected.applicant }}</strong></div><div><small>创建日期</small><strong>{{ selected.createdAt }}</strong></div><div><small>报销金额</small><strong>{{ selected.type === '报销' ? '¥' + selected.amount : '—' }}</strong></div></div><div class="drawer-section"><h3>申请说明</h3><p>{{ selected.detail }}</p></div><div v-if="selected.reviewNote" class="drawer-section"><h3>审批备注</h3><p>{{ selected.reviewNote }}</p></div><div v-if="selected.status === '草稿'" class="drawer-section"><p>提交后才会进入待审批列表。</p><button class="primary" :disabled="busy" @click="submit(selected)">提交审批 →</button></div><div v-if="selected.status === '待审批'" class="drawer-section"><h3>处理申请</h3><p class="hint">演示操作不校验实际审批身份。</p><textarea v-model="reviewNote" placeholder="审批备注（驳回时必填原因）"></textarea><div class="action-row"><button class="primary" :disabled="busy" @click="review(selected, '已通过')">同意申请 ✓</button><button class="outline" :disabled="busy || !reviewNote.trim()" @click="review(selected, '已驳回')">驳回申请</button></div></div></div></div>
  <div v-if="modal" class="overlay" @click.self="modal = false"><form class="dialog" @submit.prevent="create"><button type="button" class="close" @click="modal = false">×</button><div class="eyebrow">NEW APPLICATION</div><h2>发起新申请</h2><p>先保存为草稿，确认内容后再提交审批。</p><label>申请类型<select v-model="form.type"><option>请假</option><option>报销</option></select></label><label>申请标题<input v-model="form.title" required placeholder="例如：客户拜访交通费" /></label><label>申请人<input v-model="form.applicant" required placeholder="例如：林知夏" /></label><label>事项说明<textarea v-model="form.detail" required placeholder="请描述申请内容…"></textarea></label><label v-if="form.type === '报销'">报销金额（元）<input v-model="form.amount" type="number" min="0" required /></label><div class="dialog-actions"><button type="button" class="outline" @click="modal = false">取消</button><button class="primary" :disabled="busy">保存草稿</button></div></form></div>
</div>
</template>
