<template>
  <view class="page">
    <view class="nav"><view><text class="brand">拾光</text><text class="nav-sub">SMART CHECKOUT</text></view><text class="nav-title">订单</text></view>
    <view class="hero"><view class="hero-icon">✓</view><view><text class="eyebrow">YOUR RECEIPT</text><text class="hero-title">每次购买，都有迹可循</text><text class="hero-desc">完成自助结算后，订单会在首页底部展示商品、金额和状态。</text></view></view>
    <view class="card"><view class="card-head"><view><text class="card-title">订单记录</text><text class="card-sub">最近购买快速回顾</text></view><text class="badge">演示订单</text></view><view class="empty-row"><view class="receipt-icon">▤</view><view><text class="empty-title">订单记录在首页查看</text><text class="empty-desc">先回到首页完成商品选择与结算。</text></view><text class="arrow">→</text></view><view class="divider"></view><view class="info-grid"><view><text class="info-label">结算方式</text><text class="info-value">自助结算</text></view><view><text class="info-label">取货方式</text><text class="info-value">门店自取</text></view><view><text class="info-label">支付状态</text><text class="info-value accent">待支付</text></view></view></view>
    <view class="card tip-card"><view class="note-icon">i</view><view><text class="note-title">需要帮助？</text><text class="note-desc">演示项目默认保留本机数据，生产环境请接入会员、支付与电子小票。</text></view></view>
    <button class="primary" @click="go">返回购物 <text>→</text></button>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f4f7fb;color:#162338;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:5rpx}.nav-sub{display:block;margin-top:4rpx;color:#8b9aab;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#718195}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#145eab,#58a8e9);color:#fff;box-shadow:0 18rpx 45rpx #287fd030}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:40rpx;color:#e4f2ff}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.72}.hero-title{display:block;margin-top:8rpx;font-size:30rpx;font-weight:800;line-height:1.35}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.85}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #2238480b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#93a0af;font-size:18rpx}.badge{padding:8rpx 14rpx;border-radius:20rpx;background:#e9f4ff;color:#1c72c9;font-size:16rpx}.empty-row{display:flex;align-items:center;gap:16rpx;margin-top:27rpx}.receipt-icon,.note-icon{width:54rpx;height:54rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#e9f4ff;color:#1c72c9;font-size:27rpx;font-weight:800}.empty-title{display:block;font-size:21rpx;font-weight:700}.empty-desc{display:block;margin-top:7rpx;color:#94a1ae;font-size:18rpx}.arrow{margin-left:auto;color:#1c72c9;font-size:30rpx}.divider{height:1rpx;margin:26rpx 0;background:#edf1f4}.info-grid{display:flex;justify-content:space-between}.info-label{display:block;color:#9ba8b4;font-size:16rpx}.info-value{display:block;margin-top:8rpx;font-size:19rpx;font-weight:700}.info-value.accent{color:#e1843b}.tip-card{display:flex;align-items:center;gap:16rpx}.note-icon{background:#fff5e9;color:#c27c3d}.note-title{display:block;font-size:21rpx;font-weight:700}.note-desc{display:block;margin-top:7rpx;color:#94a1ae;font-size:18rpx;line-height:1.4}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#176fcf;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #287fd030}.primary text{margin-left:8rpx;color:#e1f1ff}
</style>