<script setup>
import { computed, onMounted, ref } from 'vue'

const active = ref('studio')
const templates = [
  { id:'landing', name:'品牌落地页', icon:'✦', html:`<main class="demo hero-demo"><span class="eyebrow">NOVA / 2026</span><h1>把灵感，做成<br><em>看得见的体验。</em></h1><p>一个面向创作者的轻量品牌工作台。</p><button>开始探索 ↗</button></main>`, css:`body{background:#101a2e;color:#f4f7ff}.hero-demo{padding:72px 12%;font-family:Arial}.eyebrow{color:#77e5c1;letter-spacing:3px;font-size:12px}.hero-demo h1{font-size:58px;line-height:1.05;margin:25px 0}.hero-demo em{color:#77e5c1;font-style:normal}.hero-demo p{color:#b5c0d7}.hero-demo button{margin-top:24px;border:0;border-radius:24px;padding:13px 23px;background:#77e5c1;color:#102039;font-weight:bold}`, js:`console.log('NOVA landing template ready')` },
  { id:'profile', name:'个人主页', icon:'◎', html:`<main class="demo profile-demo"><div class="avatar">LC</div><h1>林川 / Product Designer</h1><p>用设计让复杂的事情变得清晰、温柔、好用。</p><div class="chips"><span>产品设计</span><span>品牌系统</span><span>交互原型</span></div></main>`, css:`body{background:#fff8ef;color:#362f2a}.profile-demo{max-width:640px;margin:0 auto;padding:90px 30px;text-align:center;font-family:Arial}.avatar{margin:auto;width:80px;height:80px;border-radius:28px;display:grid;place-items:center;background:#ff826e;color:#fff;font-weight:bold;font-size:24px}.profile-demo h1{margin:25px 0 10px}.profile-demo p{color:#786c63;line-height:1.8}.chips{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:28px}.chips span{padding:9px 13px;border-radius:20px;background:#ffe0b6;font-size:13px}`, js:`document.querySelector('.avatar').onclick=()=>alert('你好，欢迎来到我的主页！')` },
  { id:'product', name:'商品卡片', icon:'▧', html:`<main class="demo product-demo"><div class="product-art">AIR<br>FLOW</div><p class="muted">AER / DAILY OBJECTS</p><h1>空气感桌面风扇</h1><p>静音、轻盈，让每一个工作日都更舒服。</p><strong>¥ 299</strong><button>加入购物车</button></main>`, css:`body{background:#f1f4f1;color:#172820}.product-demo{max-width:420px;margin:30px auto;padding:22px;font-family:Arial}.product-art{height:250px;border-radius:25px;background:linear-gradient(135deg,#cce9d6,#83bda4);display:grid;place-items:center;color:#f8fff9;font-weight:800;font-size:42px;letter-spacing:5px}.muted{color:#779184;font-size:11px;letter-spacing:2px}.product-demo h1{font-size:28px}.product-demo strong{display:block;font-size:25px;margin:20px 0}.product-demo button{border:0;background:#172820;color:#fff;border-radius:8px;padding:13px 18px}`, js:`document.querySelector('button').onclick=()=>alert('已加入演示购物车')` },
  { id:'yellow', name:'黄页卡片', icon:'▤', html:`<main class="demo yellow-demo"><p class="tag">本地服务 · 推荐</p><h1>云栖咖啡实验室</h1><p>咖啡 · 轻食 · 社区活动</p><hr><p>杭州市西湖区云栖路 18 号<br>每天 07:30 - 21:30</p><button>查看路线</button></main>`, css:`body{background:#f4f0e7;color:#262522}.yellow-demo{max-width:500px;margin:70px auto;padding:32px;border:1px solid #d8d0c1;border-radius:22px;background:#fffdf8;font-family:Arial;box-shadow:0 18px 40px #53452c18}.tag{color:#b26f28;font-size:12px}.yellow-demo h1{font-size:32px}.yellow-demo hr{border:0;border-top:1px solid #e8dfd0;margin:24px 0}.yellow-demo button{background:#b26f28;color:white;border:0;border-radius:20px;padding:11px 19px}`, js:`document.querySelector('button').onclick=()=>alert('演示：已打开地图')` }
]
const htmlCode = ref(templates[0].html), cssCode = ref(templates[0].css), jsCode = ref(templates[0].js), previewKey = ref(0)
const directory = ref([]), categories = ref(['全部']), category = ref('全部'), query = ref(''), selectedBusiness = ref(null), game = ref('tic')
const tic = ref(['','','','','','','','','']), turn = ref('X'), winner = ref(''), guess = ref(Math.floor(Math.random()*100)+1), guessInput = ref(''), guessHint = ref('请输入 1—100 的数字'), guessCount = ref(0)
const filteredDirectory = computed(() => directory.value.filter(x => (category.value === '全部' || x.category === category.value) && (x.name+x.tags+x.intro).toLowerCase().includes(query.value.toLowerCase())))
const previewSrc = computed(() => { const doc = `<!doctype html><html><head><style>${cssCode.value}</style></head><body>${htmlCode.value}<script>${jsCode.value.replace(/<\/script/gi,'<\\/script')}<\/script></body></html>`; return 'data:text/html;charset=utf-8,' + encodeURIComponent(doc) })
const winning = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
async function load() { try { directory.value = await fetch('/api/directory').then(r=>r.json()); categories.value = await fetch('/api/categories').then(r=>r.json()) } catch(e) { /* 静态演示也可使用 */ } }
function useTemplate(t) { htmlCode.value=t.html; cssCode.value=t.css; jsCode.value=t.js; previewKey.value++ ; active.value='studio' }
function resetTic() { tic.value=['','','','','','','','','']; turn.value='X'; winner.value='' }
function playTic(i) { if(tic.value[i] || winner.value) return; tic.value[i]=turn.value; const line=winning.find(([a,b,c])=>tic.value[a]&&tic.value[a]===tic.value[b]&&tic.value[a]===tic.value[c]); if(line) winner.value=turn.value+' 获胜'; else if(tic.value.every(Boolean)) winner.value='平局'; else turn.value=turn.value==='X'?'O':'X' }
function submitGuess() { const n=Number(guessInput.value); if(!n || n<1 || n>100) { guessHint.value='请输入 1—100 的整数'; return }; guessCount.value++; guessHint.value=n===guess.value?'🎉 猜中了！点击重置再来一次':n<guess.value?'再大一点 ↑':'再小一点 ↓' }
function resetGuess() { guess.value=Math.floor(Math.random()*100)+1; guessInput.value=''; guessHint.value='请输入 1—100 的数字'; guessCount.value=0 }
function nav(x) { active.value=x; selectedBusiness.value=null }
onMounted(load)
</script>
<template>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><span class="brand-mark">⌁</span><div><b>HTML / LAB</b><small>CREATIVE PLAYGROUND</small></div></div><div class="side-kicker">LOCAL CREATIVE SPACE</div><nav><button :class="{active:active==='studio'}" @click="nav('studio')"><span>⌘</span> HTML 工作台</button><button :class="{active:active==='templates'}" @click="nav('templates')"><span>◈</span> 模板灵感 <em>{{templates.length}}</em></button><button :class="{active:active==='games'}" @click="nav('games')"><span>✳</span> 小游戏中心 <em>2</em></button><button :class="{active:active==='directory'}" @click="nav('directory')"><span>▤</span> 本地黄页 <em>{{directory.length}}</em></button></nav><div class="sidebar-note"><strong>做一个能打开的想法。</strong><p>在浏览器里编辑 HTML、玩小游戏、浏览虚构黄页数据。</p><small>Vue 3 · Java 21 · 本机优先</small></div></aside>
    <main class="content"><header><span>HTML 创意工坊 <b>/</b> {{active==='studio'?'工作台':active==='templates'?'模板灵感':active==='games'?'小游戏中心':'本地黄页'}}</span><div><i></i>LOCAL PREVIEW <button class="user-dot">H</button></div></header>
      <section v-if="active==='studio'" class="page studio"><div class="title-row"><div><label>HTML / PLAYGROUND</label><h1>把网页，做成<span>可以玩的作品。</span></h1><p>三栏编辑、即时预览，写完就能分享的轻量创意工作台。</p></div><button class="primary" @click="previewKey++">刷新预览 ↗</button></div><div class="template-strip"><button v-for="t in templates" :key="t.id" @click="useTemplate(t)"><b>{{t.icon}}</b>{{t.name}}</button></div><div class="workspace"><div class="editors"><div class="editor"><div><b>HTML</b><small>结构</small></div><textarea v-model="htmlCode" spellcheck="false"></textarea></div><div class="editor"><div><b>CSS</b><small>样式</small></div><textarea v-model="cssCode" spellcheck="false"></textarea></div><div class="editor"><div><b>JS</b><small>交互</small></div><textarea v-model="jsCode" spellcheck="false"></textarea></div></div><div class="preview-panel"><div class="preview-head"><b>LIVE PREVIEW</b><span>安全沙盒 · 仅在本机渲染</span></div><iframe :key="previewKey" :src="previewSrc" sandbox="allow-scripts"></iframe></div></div></section>
      <section v-else-if="active==='templates'" class="page"><div class="title-row"><div><label>START WITH A TEMPLATE</label><h1>模板灵感<span>.</span></h1><p>先选一个方向，再把它改成你的作品。</p></div></div><div class="template-grid"><article v-for="t in templates" :key="t.id" class="template-card"><div class="mini-preview" :class="t.id"><span>{{t.icon}}</span></div><div class="template-info"><div><h2>{{t.name}}</h2><p>HTML · CSS · JavaScript</p></div><button @click="useTemplate(t)">使用模板 →</button></div></article></div></section>
      <section v-else-if="active==='games'" class="page"><div class="title-row"><div><label>SMALL GAMES / 02</label><h1>休息五分钟<span>.</span></h1><p>两个无需安装、打开就能玩的浏览器小游戏。</p></div><div class="game-switch"><button :class="{chosen:game==='tic'}" @click="game='tic'">井字棋</button><button :class="{chosen:game==='guess'}" @click="game='guess'">猜数字</button></div></div><div v-if="game==='tic'" class="game-card tic-card"><div class="game-intro"><span class="game-icon">✕</span><h2>井字棋</h2><p>两位玩家轮流落子，三子连线即可获胜。</p><strong v-if="winner">{{winner}}</strong><span v-else>当前回合：{{turn}}</span><button @click="resetTic">重新开始</button></div><div class="tic-board"><button v-for="(cell,i) in tic" :key="i" @click="playTic(i)" :class="cell.toLowerCase()">{{cell}}</button></div></div><div v-else class="game-card guess-card"><div class="guess-orb">?</div><h2>猜数字</h2><p>我已经想好了一个 1—100 的数字，你能几次猜中？</p><div class="guess-form"><input v-model="guessInput" @keyup.enter="submitGuess" placeholder="输入数字" type="number"><button @click="submitGuess">提交猜测</button></div><strong>{{guessHint}}</strong><small>已猜 {{guessCount}} 次</small><button class="text-btn" @click="resetGuess">换一个数字</button></div></section>
      <section v-else class="page"><div class="title-row"><div><label>LOCAL DIRECTORY / DEMO DATA</label><h1>附近有什么<span>好服务？</span></h1><p>这是可替换的黄页 UI 示例，数据为虚构演示，不代表真实公共信息。</p></div><div class="directory-count"><b>{{filteredDirectory.length}}</b><span>家演示商户</span></div></div><div class="directory-tools"><input v-model="query" placeholder="搜索商家、标签或服务…"><div class="category-pills"><button v-for="c in categories" :key="c" :class="{chosen:category===c}" @click="category=c">{{c}}</button></div></div><div class="directory-grid"><article v-for="item in filteredDirectory" :key="item.id" class="business-card" @click="selectedBusiness=item"><div class="business-top"><span class="business-avatar">{{item.name.slice(0,1)}}</span><span class="rating">★ {{item.rating}}</span></div><p class="business-category">{{item.category}} · {{item.tags}}</p><h2>{{item.name}}</h2><p>{{item.intro}}</p><footer><span>⌖ {{item.address}}</span><span>◷ {{item.hours}}</span></footer></article></div><div v-if="!filteredDirectory.length" class="empty">没有找到匹配的演示商户</div><div v-if="selectedBusiness" class="modal-backdrop" @click.self="selectedBusiness=null"><div class="business-detail"><button class="close" @click="selectedBusiness=null">×</button><span class="business-avatar big">{{selectedBusiness.name.slice(0,1)}}</span><p class="business-category">{{selectedBusiness.category}} · {{selectedBusiness.tags}}</p><h2>{{selectedBusiness.name}}</h2><p>{{selectedBusiness.intro}}</p><dl><dt>地址</dt><dd>{{selectedBusiness.address}}</dd><dt>营业时间</dt><dd>{{selectedBusiness.hours}}</dd><dt>电话</dt><dd>{{selectedBusiness.phone}}</dd></dl><a :href="'tel:'+selectedBusiness.phone">拨打演示电话</a></div></div></section>
      <footer class="footer">HTML / LAB · 一个为创意、原型与轻量互动而生的本机工作台 <span>不上传代码 · 不是真实黄页</span></footer>
    </main>
  </div>
</template>
