package dev.aihub.wellness;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class WellnessApplication { public static void main(String[] args){SpringApplication.run(WellnessApplication.class,args);} }
@RestController @RequestMapping("/api") class WellnessController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 WellnessController(){ metrics.put("primary","plans"); metrics.put("title","vital · 养生服务台"); metrics.put("活跃会员","1,208");metrics.put("今日打卡","734");metrics.put("课程完成率","78.2%");metrics.put("服务提醒","42"); data.computeIfAbsent("plans",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","晨光轻食计划","detail","21 天 · 饮食","status","进行中","amount","186 人")));data.computeIfAbsent("plans",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","舒压睡眠计划","detail","14 天 · 睡眠","status","进行中","amount","92 人")));data.computeIfAbsent("plans",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","四季运动计划","detail","30 天 · 运动","status","待发布","amount","54 人")));data.computeIfAbsent("checkins",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","完成打卡","detail","陈女士 · 晨间拉伸","status","连续 12 天","amount","运动")));data.computeIfAbsent("checkins",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","课程预约","detail","李先生 · 秋季食养课","status","明日 10:00","amount","中医养生")));data.computeIfAbsent("checkins",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","服务回访","detail","王女士 · 睡眠计划","status","待联系","amount","会员关怀"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}