<script setup>
import { computed, onMounted, ref } from 'vue'
const token = ref(sessionStorage.getItem('aihub.auth.token') || '')
const username = ref('admin'), password = ref('admin123'), audience = ref('ai-hub-manage')
const me = ref(null), health = ref(null), audits = ref([]), error = ref(''), busy = ref(false)
const loggedIn = computed(() => !!token.value)
async function api(path, options={}) { const response = await fetch(path, { ...options, headers: { 'Content-Type':'application/json', ...(options.headers||{}) } }); const body = await response.json().catch(()=>({})); if (!response.ok) throw new Error(body.detail || body.message || '请求失败'); return body }
async function load() { health.value = await api('/api/health'); if (token.value) { try { me.value = await api('/api/auth/me', {headers:{Authorization:`Bearer ${token.value}`}}); if(me.value.role === '管理员')audits.value=await api('/api/audit',{headers:{Authorization:`Bearer ${token.value}`}}) } catch { logout(false) } } }
async function login() { busy.value=true; error.value=''; try { const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value,audience:audience.value})}); token.value=result.accessToken; sessionStorage.setItem('aihub.auth.token',token.value); me.value=await api('/api/auth/me',{headers:{Authorization:`Bearer ${token.value}`}}); if(me.value.role === '管理员')audits.value=await api('/api/audit',{headers:{Authorization:`Bearer ${token.value}`}}) } catch(e){error.value=e.message} finally{busy.value=false} }
async function logout(clear=true){ const previous=token.value; token.value=''; me.value=null; audits.value=[]; sessionStorage.removeItem('aihub.auth.token'); if(clear && previous) { try { await api('/api/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${previous}`}}) } catch { /* Local token is still cleared even if the audit call fails. */ } } }
function copy(){ navigator.clipboard?.writeText(token.value) }
onMounted(load)
</script>
<template>
<div class="shell"><header><div class="brand"><span class="logo">盾</span><div><div class="kicker">AI-HUB SECURITY FABRIC</div><h1>安全与身份中心</h1></div></div><span class="live"><i></i> 本机演示</span></header>
<main><section class="hero"><div><p class="eyebrow">统一身份 · 授权入口 · 审计证据</p><h2>让每个业务项目，都能接入同一套安全底座。</h2><p class="sub">提供签发者发现元数据与 RSA JWT 公钥发布，先为 ai-hub 项目提供可验证的登录、受众隔离和审计闭环。</p></div><div class="hero-orbit"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><span>IAM</span></div></section>
<section class="grid"><article class="card login-card"><div class="card-head"><div><p class="eyebrow">DEMO LOGIN</p><h3>签发访问令牌</h3></div><span class="badge">演示环境</span></div><label>账号<input v-model="username" autocomplete="username"/></label><label>密码<input v-model="password" type="password" autocomplete="current-password"/></label><label>目标应用<select v-model="audience"><option>ai-hub-manage</option><option>ai-hub-demo</option></select></label><button class="primary" :disabled="busy" @click="login">{{busy?'签发中…':'登录并签发令牌'}}</button><p class="hint">仅本机演示：admin / admin123；请勿用于真实身份数据</p><p v-if="error" class="error">{{error}}</p></article>
<article class="card status-card"><div class="card-head"><div><p class="eyebrow">RUNTIME STATUS</p><h3>底座状态</h3></div><span class="status">● 正常</span></div><div class="metric"><span>签发者</span><b>{{health?.issuer || '加载中…'}}</b></div><div class="metric"><span>密钥标识</span><b>{{health?.keyId || '—'}}</b></div><div class="metric"><span>允许受众</span><b>{{health?.audiences?.join(' · ') || '—'}}</b></div><div class="metric"><span>发现文档</span><code>/.well-known/openid-configuration</code></div></article></section>
<section class="card session" v-if="me"><div class="card-head"><div><p class="eyebrow">CURRENT SESSION</p><h3>当前会话</h3></div><button class="ghost" @click="logout()">清除本页令牌</button></div><div class="session-grid"><div><span>用户</span><b>{{me.displayName}}（{{me.username}}）</b></div><div><span>角色</span><b>{{me.role}}</b></div><div><span>状态</span><b class="green">已验证</b></div></div><div class="token"><span>Bearer 令牌已签发</span><button @click="copy">复制令牌</button></div></section>
<section class="card audit"><div class="card-head"><div><p class="eyebrow">AUDIT TRAIL</p><h3>最近审计事件（仅管理员）</h3></div><span class="count">{{audits.length}} 条</span></div><div class="table"><div class="tr th"><span>时间</span><span>动作</span><span>主体</span><span>结果</span></div><div class="tr" v-for="item in audits.slice().reverse().slice(0,8)" :key="item.time+item.action"><span>{{new Date(item.time).toLocaleString('zh-CN')}}</span><span>{{item.action}}</span><span>{{item.subject}}</span><span :class="item.result==='GRANTED'?'green':'warn'">{{item.result}}</span></div><div v-if="!audits.length" class="empty">暂无审计事件</div></div></section>
</main><footer>ai-hub · 安全与身份中心 · Vue 3 + Java 21 · 本机演示，仅供本机试验 · 不得对外提供服务</footer></div>
</template>
