<template>
  <view class="page">
    <view class="nav"><view><text class="brand">拾光</text><text class="nav-sub">SMART CHECKOUT</text></view><text class="nav-title">购物袋</text></view>
    <view class="hero"><view class="hero-icon">⌁</view><view><text class="eyebrow">SCAN · PICK · GO</text><text class="hero-title">轻装出发，快速结算</text><text class="hero-desc">扫描商品、加入购物袋，确认后即可完成自助购物演示。</text></view></view>
    <view class="card"><view class="card-head"><view><text class="card-title">自助购物指南</text><text class="card-sub">不排队，也能买得更从容</text></view><text class="badge">门店自取</text></view><view class="steps"><view class="step active"><text class="step-icon">⌕</text><text class="step-name">扫商品</text><text class="step-desc">识别条码</text></view><view class="line"></view><view class="step"><text class="step-icon">＋</text><text class="step-name">加购物袋</text><text class="step-desc">检查数量</text></view><view class="line"></view><view class="step"><text class="step-icon">✓</text><text class="step-name">去结算</text><text class="step-desc">快速离店</text></view></view></view>
    <view class="card tip-card"><view class="note-icon">i</view><view><text class="note-title">购物袋就在首页底部</text><text class="note-desc">选中商品后，底部会实时显示件数、金额和库存提示。</text></view></view>
    <button class="primary" @click="go">继续购物 <text>→</text></button><text class="footnote">当前为演示结算，真实门店需接入支付与库存系统</text>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f4f7fb;color:#162338;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:5rpx}.nav-sub{display:block;margin-top:4rpx;color:#8b9aab;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#718195}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#176fd0,#50a5ed);color:#fff;box-shadow:0 18rpx 45rpx #287fd030}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:43rpx;color:#e4f2ff}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.72}.hero-title{display:block;margin-top:8rpx;font-size:30rpx;font-weight:800;line-height:1.35}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.85}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #2238480b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#93a0af;font-size:18rpx}.badge{padding:8rpx 14rpx;border-radius:20rpx;background:#e9f4ff;color:#1c72c9;font-size:16rpx}.steps{display:flex;align-items:center;margin-top:28rpx}.step{flex:1}.step-icon{display:flex;width:50rpx;height:50rpx;align-items:center;justify-content:center;border-radius:17rpx;background:#eff2f5;color:#778697;font-size:27rpx;font-weight:800}.step.active .step-icon{background:#e8f3ff;color:#1772d1}.step-name{display:block;margin-top:13rpx;font-size:20rpx;font-weight:700}.step-desc{display:block;margin-top:6rpx;color:#9aa7b4;font-size:17rpx}.line{width:24rpx;height:2rpx;margin:0 8rpx;background:#e5ebf1}.tip-card{display:flex;align-items:center;gap:16rpx}.note-icon{width:52rpx;height:52rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#fff5e9;color:#c27c3d;font-size:25rpx;font-weight:800}.note-title{display:block;font-size:21rpx;font-weight:700}.note-desc{display:block;margin-top:7rpx;color:#94a1ae;font-size:18rpx;line-height:1.4}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#176fcf;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #287fd030}.primary text{margin-left:8rpx;color:#e1f1ff}.footnote{display:block;margin-top:18rpx;text-align:center;color:#98a5b2;font-size:17rpx}
</style>