<script setup>
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { request } from '../../services/api'
const products = ref([]); const cart = ref({}); const customer = ref(''); const email = ref(''); const loading = ref(false)
const lines = computed(() => products.value.filter(p => cart.value[p.id]).map(p => ({ ...p, quantity: cart.value[p.id] })))
const count = computed(() => lines.value.reduce((n, p) => n + p.quantity, 0)); const total = computed(() => lines.value.reduce((n, p) => n + Number(p.price) * p.quantity, 0))
async function load() { cart.value = uni.getStorageSync('shop-cart') || {}; const result = await request('/api/products'); if (result.statusCode === 200) products.value = result.data }
function change(p, delta) { const next = Math.max(0, Math.min(p.stock, (cart.value[p.id] || 0) + delta)); cart.value = { ...cart.value, [p.id]: next }; uni.setStorageSync('shop-cart', cart.value) }
async function checkout() { if (!customer.value || !email.value) return uni.showToast({ title: '请填写姓名和邮箱', icon: 'none' }); loading.value = true; try { const result = await request('/api/orders', { method: 'POST', header: { 'content-type': 'application/json' }, data: { customer: customer.value, email: email.value, items: lines.value.map(p => ({ productId: p.id, quantity: p.quantity })) } }); if (result.statusCode !== 201) throw new Error(); cart.value = {}; uni.setStorageSync('shop-cart', {}); customer.value = ''; email.value = ''; uni.showModal({ title: '下单成功', content: `演示订单 #${result.data.id} 已创建`, showCancel: false }) } catch { uni.showToast({ title: '下单失败，请刷新重试', icon: 'none' }) } finally { loading.value = false } }
onShow(load)
</script>
<template><view class="page"><view class="summary"><text>购物车（{{ count }}）</text><text>合计 <b>¥{{ total.toFixed(2) }}</b></text></view><view v-if="!lines.length" class="empty">购物车还是空的，去首页挑选好物吧。</view><view v-for="p in lines" :key="p.id" class="line"><view :class="['visual',p.color]">{{ p.icon }}</view><view class="line-info"><text class="name">{{ p.name }}</text><text class="price">¥{{ Number(p.price).toFixed(2) }}</text><view class="qty"><button @tap="change(p,-1)">−</button><text>{{ p.quantity }}</text><button @tap="change(p,1)">+</button></view></view><text class="line-total">¥{{ (Number(p.price)*p.quantity).toFixed(2) }}</text></view><view v-if="lines.length" class="checkout"><text class="title">订单信息</text><input v-model="customer" placeholder="姓名"/><input v-model="email" type="text" placeholder="邮箱"/><button :disabled="loading" @tap="checkout">{{ loading ? '提交中...' : '提交演示订单 ¥'+total.toFixed(2) }}</button></view></view></template>
<style scoped>
.page{min-height:100vh;background:#f5f5f5;padding-bottom:40rpx}.summary{height:100rpx;background:#fff;padding:0 28rpx;display:flex;align-items:center;justify-content:space-between;font-size:27rpx}.summary b{color:#e1251b}.empty{text-align:center;color:#888;padding:160rpx 30rpx}.line{display:flex;align-items:center;gap:18rpx;background:#fff;margin-top:2rpx;padding:24rpx}.visual{width:150rpx;height:150rpx;display:flex;align-items:center;justify-content:center;font-size:70rpx}.peach{background:#f4dfcb}.sage{background:#dce9d5}.lilac{background:#e4dfeb}.sand{background:#ede5d4}.blue{background:#d6e2e9}.rose{background:#f2e0df}.line-info{flex:1}.name{display:block;font-size:27rpx;font-weight:bold}.price{display:block;color:#e1251b;font-size:25rpx;margin-top:12rpx}.qty{display:flex;align-items:center;gap:20rpx;margin-top:14rpx}.qty button{width:44rpx;height:44rpx;line-height:40rpx;padding:0}.line-total{font-size:25rpx;color:#e1251b}.checkout{background:#fff;margin-top:20rpx;padding:28rpx}.title{display:block;font-size:29rpx;font-weight:bold;margin-bottom:20rpx}.checkout input{height:76rpx;border-bottom:1rpx solid #ddd;margin-bottom:14rpx;font-size:25rpx}.checkout button{background:#e1251b;color:#fff;margin-top:12rpx}
</style>
