<template>
  <view class="page">
    <view class="nav"><view><text class="brand">食刻</text><text class="nav-sub">TABLE SERVICE</text></view><text class="nav-title">餐篮</text></view>
    <view class="hero"><view class="hero-icon">＋</view><view><text class="eyebrow">ORDER YOUR WAY</text><text class="hero-title">想吃什么，随时加进餐篮</text><text class="hero-desc">浏览菜单时点击加号，菜品和总价会在底部实时更新。</text></view></view>
    <view class="card"><view class="card-head"><view><text class="card-title">点餐小贴士</text><text class="card-sub">让每一份选择都更从容</text></view><text class="badge">扫码点餐</text></view><view class="tips"><view class="tip"><text class="tip-icon">01</text><view><text class="tip-title">先选分类</text><text class="tip-desc">招牌菜、主食、小吃、饮品</text></view></view><view class="tip"><text class="tip-icon">02</text><view><text class="tip-title">调整数量</text><text class="tip-desc">点击加减，实时查看小计</text></view></view><view class="tip"><text class="tip-icon">03</text><view><text class="tip-title">确认下单</text><text class="tip-desc">备注口味，提交给后厨</text></view></view></view></view>
    <view class="card tip-card"><view class="note-icon">i</view><view><text class="note-title">同桌多人可一起点</text><text class="note-desc">每位客人都可以扫码进入本桌菜单，订单会统一汇总。</text></view></view>
    <button class="primary" @click="go">继续点餐 <text>→</text></button><text class="footnote">当前餐桌下单后，订单状态会在点餐页展示</text>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f6f7fb;color:#291c1a;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:5rpx}.nav-sub{display:block;margin-top:4rpx;color:#aa9a96;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#8f7c77}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#9f3f33,#e37450);color:#fff;box-shadow:0 18rpx 45rpx #ba594030}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:40rpx;color:#ffe8de}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.72}.hero-title{display:block;margin-top:8rpx;font-size:30rpx;font-weight:800;line-height:1.35}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.85}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #55352e0b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#a4948f;font-size:18rpx}.badge{padding:8rpx 14rpx;border-radius:20rpx;background:#fff1eb;color:#c8583e;font-size:16rpx}.tips{margin-top:26rpx}.tip{display:flex;align-items:center;gap:16rpx;padding:18rpx 0;border-bottom:1rpx solid #f1ecea}.tip:last-child{border-bottom:0;padding-bottom:0}.tip-icon{width:50rpx;height:50rpx;display:flex;align-items:center;justify-content:center;border-radius:17rpx;background:#fff0eb;color:#c85b43;font-size:17rpx;font-weight:800}.tip-title,.note-title{display:block;font-size:21rpx;font-weight:700}.tip-desc,.note-desc{display:block;margin-top:7rpx;color:#998d89;font-size:18rpx}.tip-card{display:flex;align-items:center;gap:16rpx}.note-icon{width:52rpx;height:52rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#fff5e9;color:#c27c3d;font-size:25rpx;font-weight:800}.note-desc{line-height:1.4}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#a84235;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #ad4b3a30}.primary text{margin-left:8rpx;color:#ffe1d7}.footnote{display:block;margin-top:18rpx;text-align:center;color:#aa9d99;font-size:17rpx}
</style>