<script setup>
import { computed, onMounted, ref } from 'vue'
import UserTable from './components/UserTable.vue'
import PageHeading from './components/PageHeading.vue'

const page = ref('控制台')
const users = ref([]), roles = ref([]), menus = ref([]), departments = ref([]), logs = ref([])
const metrics = ref({ users: 0, active: 0, roles: 0, departments: 0 })
const profile = ref({ name: '林晓雨', email: 'xiaoyu@example.com', role: '超级管理员', department: '产品研发', phone: '138****8000', lastLogin: '2026-10-01 09:42:18' })
const search = ref(''), statusFilter = ref('全部状态'), modal = ref(false), editing = ref(null), error = ref(''), loading = ref(true)
const collapsed = ref(false), mobileOpen = ref(false), profileOpen = ref(false), noticeOpen = ref(false)
const form = ref({ name:'', email:'', role:'编辑', department:'产品研发', status:'正常' })
const nav = [
  { label: '控制台', icon: '▦', group: '工作台' },
  { label: '用户管理', icon: '♙', group: '系统管理' },
  { label: '角色管理', icon: '♧', group: '系统管理' },
  { label: '菜单管理', icon: '☷', group: '系统管理' },
  { label: '部门管理', icon: '⌘', group: '系统管理' },
  { label: '操作日志', icon: '≡', group: '系统监控' },
  { label: '个人中心', icon: '◎', group: '个人设置' }
]
const groups = ['工作台', '系统管理', '系统监控', '个人设置']
const filtered = computed(() => users.value.filter(u => (statusFilter.value === '全部状态' || u.status === statusFilter.value) && [u.name,u.email,u.department,u.role].some(v => v.toLowerCase().includes(search.value.toLowerCase()))))
const recent = computed(() => users.value.slice(-5).reverse())
const date = new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())
const pageMeta = computed(() => ({
  '控制台': ['首页', '欢迎回来，林晓雨'], '用户管理': ['系统管理 / 用户管理', '用户管理'], '角色管理': ['系统管理 / 角色管理', '角色管理'], '菜单管理': ['系统管理 / 菜单管理', '菜单管理'], '部门管理': ['系统管理 / 部门管理', '部门管理'], '操作日志': ['系统监控 / 操作日志', '操作日志'], '个人中心': ['个人设置 / 个人中心', '个人中心']
}[page.value]))
async function api(path, options) { const r = await fetch(path, options); if (!r.ok) throw new Error('请求失败'); return r.status === 204 ? null : r.json() }
async function load() { loading.value = true; try { const [u,r,m,d,l,p] = await Promise.all(['/api/users','/api/roles','/api/menus','/api/departments','/api/logs','/api/profile'].map(path => api(path))); users.value=u; roles.value=r; menus.value=m; departments.value=d; logs.value=l; profile.value=p; metrics.value=await api('/api/metrics'); error.value='' } catch (e) { error.value='服务暂不可用，请启动 manage/backend 后刷新。' } finally { loading.value=false } }
function go(label) { page.value=label; mobileOpen.value=false; profileOpen.value=false; noticeOpen.value=false }
function openCreate(){ editing.value=null; form.value={name:'',email:'',role:'编辑',department:'产品研发',status:'正常'}; modal.value=true }
function openEdit(u){ editing.value=u.id; form.value={name:u.name,email:u.email,role:u.role,department:u.department,status:u.status}; modal.value=true }
async function save(){ try { await api(editing.value ? '/api/users/'+editing.value : '/api/users',{method:editing.value?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)}); modal.value=false; await load() } catch(e) { error.value='保存失败：邮箱可能已存在或表单不完整' } }
async function remove(u){ if(!confirm('确定删除 '+u.name+' 吗？')) return; try { await api('/api/users/'+u.id,{method:'DELETE'}); await load() } catch { error.value='删除失败' } }
function exportLogs(){ const csv=['操作人,操作,模块,IP,时间,状态',...logs.value.map(x=>[x.operator,x.action,x.module,x.ip,x.time,x.status].join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'})); a.download='操作日志.csv'; a.click(); URL.revokeObjectURL(a.href) }
onMounted(load)
</script>
<template>
<div class="app-shell" :class="{collapsed, 'mobile-open': mobileOpen}">
  <div class="mobile-mask" v-if="mobileOpen" @click="mobileOpen=false"></div>
  <aside class="sidebar">
    <div class="brand"><span class="brand-mark">A</span><div class="brand-text"><b>ai-hub</b><small>ADMIN CONSOLE</small></div><button class="collapse-btn" @click="collapsed=!collapsed">‹</button></div>
    <div class="workspace-switch"><span class="workspace-mark">A</span><div><b>ai-hub 管理后台</b><small>演示环境</small></div><span class="chevron">⌄</span></div>
    <div v-for="group in groups" :key="group" class="nav-group"><div class="nav-title">{{group}}</div><button v-for="item in nav.filter(n=>n.group===group)" :key="item.label" :class="{active:page===item.label}" @click="go(item.label)"><span class="nav-icon">{{item.icon}}</span><span class="nav-label">{{item.label}}</span><span v-if="item.label==='用户管理' && page!=='用户管理'" class="nav-badge">8</span></button></div>
    <div class="sidebar-bottom"><div class="help-card"><span class="help-star">✦</span><b>需要帮助？</b><small>查看使用文档和接口说明</small><a href="mailto:3174667330@qq.com">联系我们 ↗</a></div><div class="side-user"><span class="avatar avatar-orange">林</span><div class="nav-label"><b>林晓雨</b><small>超级管理员</small></div><span class="more">···</span></div></div>
  </aside>
  <section class="main-area">
    <header class="topbar"><button class="mobile-menu" @click="mobileOpen=true">☰</button><div class="crumb"><span>{{pageMeta[0]}}</span><b>/</b><strong>{{pageMeta[1]}}</strong></div><div class="top-actions"><div class="global-search">⌕ <span>搜索菜单、用户</span><kbd>⌘ K</kbd></div><button class="icon-btn" @click="noticeOpen=!noticeOpen">♢<i></i></button><div class="top-profile" @click="profileOpen=!profileOpen"><span class="avatar avatar-orange">林</span><span class="top-name">林晓雨</span><span class="down">⌄</span><div v-if="profileOpen" class="profile-pop"><b>林晓雨</b><small>超级管理员</small><hr><button @click.stop="go('个人中心')">个人中心</button><button>退出登录</button></div></div><div v-if="noticeOpen" class="notice-pop"><b>通知中心</b><p>暂无未读通知</p></div></div></header>
    <main class="content">
      <div v-if="error" class="error-banner">{{error}}<button @click="error=''">×</button></div>
      <template v-if="page==='控制台'"><div class="heading welcome"><div><div class="eyebrow">WORKSPACE OVERVIEW</div><h1>早上好，林晓雨 <span>✳</span></h1><p>今天是 {{date}}，这里是你的工作空间概览。</p></div><button class="outline-btn" @click="go('用户管理')">查看用户管理 ↗</button></div>
        <div class="metrics"><div class="metric"><div class="metric-top"><span class="metric-icon purple">♙</span><span class="trend">+12.5% ↗</span></div><small>用户总数</small><strong>{{metrics.users}}<em> 位</em></strong><p>较上月新增用户</p></div><div class="metric"><div class="metric-top"><span class="metric-icon green">✓</span><span class="trend green-text">+8.2% ↗</span></div><small>活跃用户</small><strong>{{metrics.active}}<em> 位</em></strong><p>当前状态正常的成员</p></div><div class="metric"><div class="metric-top"><span class="metric-icon orange">♧</span><span class="trend orange-text">稳定</span></div><small>角色配置</small><strong>{{metrics.roles}}<em> 种</em></strong><p>覆盖不同业务权限</p></div><div class="metric"><div class="metric-top"><span class="metric-icon blue">⌘</span><span class="trend blue-text">+2 本月</span></div><small>组织部门</small><strong>{{metrics.departments}}<em> 个</em></strong><p>清晰的组织架构</p></div></div>
        <div class="dashboard-grid"><section class="panel chart-panel"><div class="panel-title"><div><h2>访问趋势</h2><p>近 7 天工作台访问概况</p></div><select><option>最近 7 天</option><option>最近 30 天</option></select></div><div class="chart"><div class="y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div class="chart-area"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 700 210" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7466dc" stop-opacity=".25"/><stop offset="1" stop-color="#7466dc" stop-opacity="0"/></linearGradient></defs><path d="M0 168 C45 150 50 110 105 125 S165 165 210 112 S265 100 315 132 S355 84 405 100 S465 128 505 76 S565 45 610 78 S665 45 700 20 L700 210 L0 210Z" fill="url(#fill)"/><path d="M0 168 C45 150 50 110 105 125 S165 165 210 112 S265 100 315 132 S355 84 405 100 S465 128 505 76 S565 45 610 78 S665 45 700 20" fill="none" stroke="#7466dc" stroke-width="3"/></svg><div class="x-labels"><span>周一</span><span>周二</span><span>周三</span><span>周四</span><span>周五</span><span>周六</span><span>周日</span></div></div></div></section><section class="panel quick-panel"><div class="panel-title"><div><h2>快捷操作</h2><p>快速完成日常管理任务</p></div></div><button @click="openCreate"><span class="quick-icon purple">＋</span><span><b>添加新用户</b><small>邀请成员加入工作空间</small></span><strong>↗</strong></button><button @click="go('角色管理')"><span class="quick-icon blue">♧</span><span><b>管理角色</b><small>查看角色与权限说明</small></span><strong>↗</strong></button><button @click="go('操作日志')"><span class="quick-icon orange">≡</span><span><b>查看操作日志</b><small>追踪系统关键操作</small></span><strong>↗</strong></button><div class="tip">✦ &nbsp; 好的团队管理，让每个人都能专注于重要的事。</div></section></div>
        <section class="panel recent-panel"><div class="panel-title"><div><h2>最近成员</h2><p>工作空间中的团队伙伴</p></div><button class="text-btn" @click="go('用户管理')">查看全部 →</button></div><UserTable :rows="recent" :compact="true" @edit="openEdit" /></section>
      </template>
      <template v-else-if="page==='用户管理'"><div class="heading"><div><div class="eyebrow">SYSTEM / USER</div><h1>用户管理</h1><p>管理成员资料、角色、部门及访问状态。</p></div><button class="primary-btn" @click="openCreate">＋ 添加用户</button></div><section class="panel list-panel"><div class="list-toolbar"><div><h2>用户列表 <span class="count">{{filtered.length}}</span></h2><p>支持按姓名、邮箱或部门快速检索</p></div><div class="controls"><input v-model="search" placeholder="⌕  搜索用户"/><select v-model="statusFilter"><option>全部状态</option><option>正常</option><option>停用</option></select><button class="filter-btn">筛选</button></div></div><UserTable :rows="filtered" @edit="openEdit" @remove="remove" /></section></template>
      <template v-else-if="page==='角色管理'"><PageHeading eyebrow="SYSTEM / ROLE" title="角色管理" desc="配置角色职责与数据权限，建立清晰的访问边界。"/><div class="role-grid"><section v-for="(r,i) in roles" :key="r.name" class="panel role-card"><div class="role-head"><span class="role-symbol" :class="['purple','blue','orange','green'][i]">{{['✦','◈','✎','◉'][i]}}</span><span class="status-pill">正常</span></div><h2>{{r.name}}</h2><p>{{r.description}}</p><div class="role-foot"><span>{{r.scope}}</span><b>{{r.members}} 位成员　→</b></div></section></div></template>
      <template v-else-if="page==='菜单管理'"><PageHeading eyebrow="SYSTEM / MENU" title="菜单管理" desc="维护系统菜单、路由地址和权限标识。"/><section class="panel list-panel"><div class="list-toolbar simple"><div><h2>菜单列表 <span class="count">{{menus.length}}</span></h2><p>当前展示系统菜单与操作权限</p></div><button class="primary-btn">＋ 新增菜单</button></div><div class="table-wrap"><table><thead><tr><th>菜单名称</th><th>类型</th><th>路由地址</th><th>权限标识</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="m in menus" :key="m.id"><td><b class="tree-indent" :class="{root:m.type==='目录'}">{{m.type==='目录'?'⌄':'└'}} {{m.name}}</b></td><td><span class="type-tag">{{m.type}}</span></td><td class="mono">{{m.path}}</td><td class="mono muted">{{m.permission}}</td><td><span class="status-dot good">● 正常</span></td><td><button class="row-action">编辑</button></td></tr></tbody></table></div></section></template>
      <template v-else-if="page==='部门管理'"><PageHeading eyebrow="SYSTEM / DEPARTMENT" title="部门管理" desc="维护组织架构与部门负责人信息。"/><section class="panel list-panel"><div class="list-toolbar simple"><div><h2>组织架构 <span class="count">{{departments.length}}</span></h2><p>部门人数随用户数据实时统计</p></div><button class="primary-btn">＋ 新增部门</button></div><div class="table-wrap"><table><thead><tr><th>部门名称</th><th>负责人</th><th>成员数</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="d in departments" :key="d.id"><td><b class="tree-indent">⌄ {{d.name}}</b></td><td>{{d.leader}}</td><td><strong>{{d.members}}</strong> 人</td><td><span class="status-dot good">● {{d.status}}</span></td><td><button class="row-action">编辑</button><button class="row-action danger">删除</button></td></tr></tbody></table></div></section></template>
      <template v-else-if="page==='操作日志'"><PageHeading eyebrow="MONITOR / LOG" title="操作日志" desc="记录后台用户的关键操作，便于追溯与审计。"/><section class="panel list-panel"><div class="list-toolbar simple"><div><h2>操作记录 <span class="count">{{logs.length}}</span></h2><p>最近更新：2026 年 10 月 1 日 09:42</p></div><button class="outline-btn" @click="exportLogs">⇩ 导出日志</button></div><div class="table-wrap"><table><thead><tr><th>操作人</th><th>操作内容</th><th>所属模块</th><th>IP 地址</th><th>操作时间</th><th>结果</th></tr></thead><tbody><tr v-for="l in logs" :key="l.id"><td><div class="person"><span class="avatar avatar-purple">{{l.operator.slice(0,1)}}</span><b>{{l.operator}}</b></div></td><td>{{l.action}}</td><td><span class="module-tag">{{l.module}}</span></td><td class="mono">{{l.ip}}</td><td class="mono muted">{{l.time}}</td><td><span class="status-dot" :class="l.status==='成功'?'good':'bad'">● {{l.status}}</span></td></tr></tbody></table></div></section></template>
      <template v-else><PageHeading eyebrow="PERSONAL / PROFILE" title="个人中心" desc="查看和维护当前登录用户的个人资料。"/><div class="profile-grid"><section class="panel profile-card"><div class="profile-cover"></div><div class="profile-main"><span class="profile-avatar">林</span><h2>{{profile.name}}</h2><p>{{profile.role}} · {{profile.department}}</p><div class="profile-actions"><button class="primary-btn">编辑资料</button><button class="outline-btn">修改密码</button></div></div></section><section class="panel detail-card"><h2>基本资料</h2><div class="detail-row"><span>登录账号</span><b>{{profile.email}}</b></div><div class="detail-row"><span>手机号码</span><b>{{profile.phone}}</b></div><div class="detail-row"><span>所属部门</span><b>{{profile.department}}</b></div><div class="detail-row"><span>最后登录</span><b>{{profile.lastLogin}}</b></div></section></div></template>
      <div v-if="loading" class="loading">正在加载工作台数据…</div>
    </main><footer>© 2026 ai-hub · 通用管理后台 <span>Vue 3 + Java 21 · RuoYi-style starter</span></footer>
  </section>
</div>
<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="modal" @submit.prevent="save"><div class="modal-header"><div><div class="eyebrow">SYSTEM / USER</div><h2>{{editing ? '编辑用户' : '添加用户'}}</h2></div><button type="button" @click="modal=false">×</button></div><label>姓名<input v-model="form.name" required placeholder="请输入姓名"/></label><label>邮箱<input v-model="form.email" required type="email" placeholder="name@example.com"/></label><div class="form-grid"><label>角色<select v-model="form.role"><option v-for="r in roles" :key="r.name">{{r.name}}</option></select></label><label>状态<select v-model="form.status"><option>正常</option><option>停用</option></select></label></div><label>部门<input v-model="form.department" required placeholder="所属部门"/></label><div class="modal-actions"><button type="button" class="outline-btn" @click="modal=false">取消</button><button class="primary-btn">保存用户</button></div></form></div>
</template>
