package dev.aihub.health;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class HealthApplication { public static void main(String[] args){SpringApplication.run(HealthApplication.class,args);} }
@RestController @RequestMapping("/api") class HealthController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 HealthController(){ metrics.put("primary","members"); metrics.put("title","care · 健康管理台"); metrics.put("管理人数","2,486");metrics.put("本周随访","128");metrics.put("达标率","86.4%");metrics.put("待提醒","27"); data.computeIfAbsent("members",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","林女士","detail","血压管理 · 42 岁","status","稳定","amount","上次 09-28")));data.computeIfAbsent("members",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","周先生","detail","体重管理 · 35 岁","status","改善","amount","上次 09-29")));data.computeIfAbsent("members",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","赵女士","detail","睡眠管理 · 29 岁","status","关注","amount","上次 09-30")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","复诊提醒","detail","林女士 · 血压复查","status","今日 14:00","amount","心内科")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","指标达标","detail","周先生 · 体重目标","status","连续 7 天","amount","已完成")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","健康问卷","detail","赵女士 · 睡眠评估","status","待填写","amount","线上"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}