package dev.aihub.hospital;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class HospitalApplication { public static void main(String[] args){SpringApplication.run(HospitalApplication.class,args);} }
@RestController @RequestMapping("/api") class HospitalController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 HospitalController(){ metrics.put("primary","patients"); metrics.put("title","medix · 医院运营台"); metrics.put("今日门诊","1,286");metrics.put("在院患者","342");metrics.put("床位使用率","82.6%");metrics.put("待处理医嘱","18"); data.computeIfAbsent("patients",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","张某某","detail","心内科 · 住院 03-28","status","治疗中","amount","A-1208")));data.computeIfAbsent("patients",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","李某某","detail","骨科 · 待复诊","status","待复查","amount","B-0602")));data.computeIfAbsent("patients",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","王某某","detail","消化科 · 门诊","status","已完成","amount","门诊-3")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","门诊签到","detail","张医生 · 心内科","status","已签到","amount","32 人")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","检查报告","detail","影像科 · 08:30 批次","status","待审核","amount","8 份")));data.computeIfAbsent("appointments",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","病区交班","detail","3 号病区 · 夜班","status","已完成","amount","无异常"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}