"""Additional independent industry demo definitions. Same field schema as create-sector.py."""
EXTRA = [
 ('property',8104,'物业房产','PROPERTY ONE','楼宇、房源与服务请求，形成可追溯的管理台账','#247ca3','#e9f4fb',[
   ('units','房源档案','▦',[('code','房源编号','text',1),('building','楼栋','text',1),('floor','楼层','number',1),('area','面积（㎡）','money',1),('occupant','住户／租户','text',1)],{'code':'A-1201','building':'演示楼宇 A','floor':12,'area':89.5,'occupant':'演示住户'}),
   ('requests','报修工单','✦',[('unitId','关联房源','relation',1,'units'),('title','报修事项','text',1),('reportedAt','报修日期','date',1),('priority','优先级','select',1,['一般','紧急']),('status','处理状态','select',1,['待受理','处理中','已完成']),('notes','处理备注','textarea',0)],{'unitId':1,'title':'公共照明检查','reportedAt':'2026-10-01','priority':'一般','status':'处理中','notes':'虚构报修'})]),
 ('agriculture',8105,'农业养殖','FIELD NOTES','地块、作物与农事记录，让田间信息不再散落','#63853c','#f0f7e7',[
   ('plots','地块档案','▦',[('code','地块编号','text',1),('crop','作物／品种','text',1),('area','面积（亩）','money',1),('manager','负责人','text',1),('status','地块状态','select',1,['备耕','种植中','已收获'])],{'code':'田块-01','crop':'水稻','area':12.5,'manager':'演示农场','status':'种植中'}),
   ('activities','农事记录','✦',[('plotId','关联地块','relation',1,'plots'),('date','作业日期','date',1),('type','作业类型','select',1,['播种','灌溉','施肥','巡查','收获']),('quantity','投入量','number',1),('notes','作业详情','textarea',0)],{'plotId':1,'date':'2026-10-01','type':'巡查','quantity':1,'notes':'虚构田间巡查'})]),
 ('construction',8106,'建筑工程','BUILD GRID','项目节点和施工日志，清楚呈现现场交付进度','#b97830','#fff2e7',[
   ('projects','工程项目','▣',[('code','项目编号','text',1),('name','项目名称','text',1),('site','施工地点','text',1),('manager','项目负责人','text',1),('dueDate','计划完工','date',1),('status','项目状态','select',1,['筹备','施工中','验收中','已完成'])],{'code':'BUILD-01','name':'社区活动中心改造','site':'演示园区','manager':'王工','dueDate':'2026-12-20','status':'施工中'}),
   ('siteLogs','施工日志','▤',[('projectId','关联项目','relation',1,'projects'),('date','记录日期','date',1),('phase','施工阶段','text',1),('crew','现场人数','number',1),('risk','安全风险','select',1,['无异常','待整改','已整改']),('notes','现场记录','textarea',0)],{'projectId':1,'date':'2026-10-01','phase':'结构施工','crew':12,'risk':'无异常','notes':'虚构施工日志'})]),
 ('hospitality',8107,'酒店旅游','STAY STUDIO','房态与预订一目了然，轻量管理每一次到店体验','#a34a83','#fdeef7',[
   ('rooms','客房档案','▦',[('number','房号','text',1),('type','房型','select',1,['标准间','大床房','套房']),('rate','参考房价','money',1),('status','房态','select',1,['可预订','维修中','已停用'])],{'number':'1208','type':'大床房','rate':399,'status':'可预订'}),
   ('bookings','预订记录','✦',[('roomId','关联客房','relation',1,'rooms'),('guest','客人称呼','text',1),('checkIn','入住日期','date',1),('checkOut','离店日期','date',1),('status','预订状态','select',1,['待确认','已确认','已入住','已退房','已取消']),('notes','预订备注','textarea',0)],{'roomId':1,'guest':'演示访客','checkIn':'2026-10-10','checkOut':'2026-10-12','status':'已确认','notes':'虚构预订'})]),
 ('hrm',8108,'人力资源','PEOPLE DESK','员工档案与假勤申请，面向小团队的清爽人事工作台','#5767ad','#edf1ff',[
   ('employees','员工档案','▦',[('employeeNo','员工编号','text',1),('name','姓名','text',1),('department','部门','text',1),('role','岗位','text',1),('joinDate','入职日期','date',1),('status','在职状态','select',1,['在职','休假','离职'])],{'employeeNo':'EMP-001','name':'演示员工','department':'产品部','role':'运营','joinDate':'2026-01-01','status':'在职'}),
   ('leaveRequests','假勤申请','✦',[('employeeId','申请员工','relation',1,'employees'),('startDate','开始日期','date',1),('endDate','结束日期','date',1),('type','请假类型','select',1,['年假','事假','病假','调休']),('status','审批状态','select',1,['待审批','已通过','已驳回']),('notes','申请说明','textarea',0)],{'employeeId':1,'startDate':'2026-10-12','endDate':'2026-10-13','type':'年假','status':'待审批','notes':'虚构请假'})]),
 ('service',8109,'售后工单','SERVICE LOOP','从报修、派单到完成，跟踪服务请求的每一步','#d1664c','#fff0e9',[
   ('customers','客户档案','▦',[('code','客户编号','text',1),('name','客户名称','text',1),('contact','联系方式','text',1),('region','所在区域','text',1)],{'code':'CUS-01','name':'演示客户','contact':'仅演示，无真实号码','region':'华东'}),
   ('tickets','服务工单','✦',[('customerId','关联客户','relation',1,'customers'),('ticketNo','工单编号','text',1),('subject','服务主题','text',1),('priority','优先级','select',1,['普通','紧急']),('status','处理状态','select',1,['待受理','已派单','处理中','已解决']),('dueDate','期望完成','date',1),('notes','处理记录','textarea',0)],{'customerId':1,'ticketNo':'TKT-001','subject':'设备故障排查','priority':'普通','status':'处理中','dueDate':'2026-10-08','notes':'虚构服务工单'})]),
 ('energy',8110,'能源环保','ECO MONITOR','设备与巡检指标并排可见，异常线索及时记录','#167e75','#e5f7f3',[
   ('assets','监测设备','▦',[('code','设备编号','text',1),('name','设备名称','text',1),('site','安装位置','text',1),('type','设备类型','select',1,['能耗表','水质仪','空气传感器']),('status','运行状态','select',1,['正常','检修','停用'])],{'code':'ECO-01','name':'园区能耗表','site':'演示园区','type':'能耗表','status':'正常'}),
   ('inspections','巡检记录','✦',[('assetId','关联设备','relation',1,'assets'),('date','巡检日期','date',1),('reading','读数','money',1),('result','巡检结论','select',1,['正常','待复核','异常']),('inspector','巡检人','text',1),('notes','巡检备注','textarea',0)],{'assetId':1,'date':'2026-10-01','reading':125.3,'result':'正常','inspector':'演示巡检员','notes':'虚构读数，非实时监测'})]),
 ('legal',8111,'法律服务','CASE FILE','委托事项与案件进度集中整理，避免关键节点遗漏','#554b82','#f1eef9',[
   ('clients','委托人档案','▦',[('code','委托编号','text',1),('name','委托人称呼','text',1),('caseType','业务类型','text',1),('contact','联系信息','text',1)],{'code':'CLI-01','name':'演示委托人','caseType':'合同咨询','contact':'演示数据'}),
   ('cases','案件进度','✦',[('clientId','关联委托人','relation',1,'clients'),('caseNo','案件编号','text',1),('title','事项名称','text',1),('openedAt','受理日期','date',1),('stage','当前阶段','select',1,['咨询','材料准备','办理中','已结案']),('nextAction','下一步行动','text',1),('notes','案件备注','textarea',0)],{'clientId':1,'caseNo':'CASE-01','title':'合同审阅演示','openedAt':'2026-10-01','stage':'材料准备','nextAction':'整理材料','notes':'虚构案例，非法律意见'})]),
 ('culture',8112,'文化体育','VENUE FLOW','场馆与活动预约，让空间使用安排清楚可见','#b15b6c','#fff0f2',[
   ('venues','场馆空间','▦',[('code','场馆编号','text',1),('name','场馆名称','text',1),('capacity','容纳人数','number',1),('type','场馆类型','select',1,['展厅','球馆','排练室','会议室']),('status','使用状态','select',1,['开放','维护','暂停'])],{'code':'VEN-01','name':'社区多功能厅','capacity':80,'type':'展厅','status':'开放'}),
   ('events','活动安排','✦',[('venueId','关联场馆','relation',1,'venues'),('title','活动名称','text',1),('organizer','主办方','text',1),('date','活动日期','date',1),('attendees','预计人数','number',1),('status','活动状态','select',1,['筹备中','已确认','已完成','已取消']),('notes','活动备注','textarea',0)],{'venueId':1,'title':'周末科学体验','organizer':'演示社区','date':'2026-10-12','attendees':40,'status':'已确认','notes':'虚构活动'})]),
 ('community',8113,'社区公益','NEIGHBOR HUB','居民需求与志愿服务，用可追踪的小事连接社区','#35759d','#eaf5fc',[
   ('programs','服务项目','▦',[('code','项目编号','text',1),('name','项目名称','text',1),('category','项目类型','select',1,['便民','志愿','关怀','活动']),('coordinator','负责人','text',1),('status','项目状态','select',1,['筹备','开放','已结束'])],{'code':'COM-01','name':'社区助老服务','category':'关怀','coordinator':'演示志愿者','status':'开放'}),
   ('requests','服务需求','✦',[('programId','关联项目','relation',1,'programs'),('title','需求摘要','text',1),('submittedAt','登记日期','date',1),('urgency','紧急程度','select',1,['一般','紧急']),('status','处理状态','select',1,['待受理','进行中','已完成']),('notes','处理备注','textarea',0)],{'programId':1,'title':'上门协助申请','submittedAt':'2026-10-01','urgency':'一般','status':'待受理','notes':'虚构需求，不含真实个人信息'})]),
]
