<template>
  <view class="page">
    <view class="nav"><view><text class="brand">LUNE</text><text class="nav-sub">HAIR STUDIO</text></view><text class="nav-title">我的预约</text></view>
    <view class="hero"><view class="hero-icon">♡</view><view><text class="eyebrow">MY APPOINTMENTS</text><text class="hero-title">每一次改变，都值得被期待</text><text class="hero-desc">输入预约手机号，即可在首页查看服务、时间与取消入口。</text></view></view>
    <view class="card"><view class="card-head"><view><text class="card-title">预约管理</text><text class="card-sub">服务状态一目了然</text></view><text class="badge">在线查询</text></view><view class="status-row"><view class="status-icon">⌕</view><view><text class="status-title">从首页查询预约</text><text class="status-desc">预约手机号是你的专属查询凭证</text></view><text class="arrow">→</text></view><view class="divider"></view><view class="info-grid"><view><text class="info-label">营业时间</text><text class="info-value">10:00—20:00</text></view><view><text class="info-label">预约提前</text><text class="info-value">最多 14 天</text></view><view><text class="info-label">到店提醒</text><text class="info-value">提前 15 分钟</text></view></view></view>
    <view class="card help"><view class="help-icon">?</view><view><text class="help-title">需要调整预约？</text><text class="help-desc">在首页输入手机号后，可取消未开始的预约，再重新选择时间。</text></view></view>
    <button class="primary" @click="go">去查看预约 <text>→</text></button>
  </view>
</template>
<script setup>
function go(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style scoped>
.page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f5f7fb;color:#162c24;box-sizing:border-box}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:block;font-size:28rpx;font-weight:900;letter-spacing:6rpx}.nav-sub{display:block;margin-top:4rpx;color:#94a199;font-size:14rpx;letter-spacing:2rpx}.nav-title{font-size:22rpx;color:#738078}.hero{display:flex;align-items:center;gap:22rpx;margin-top:28rpx;padding:28rpx;border-radius:28rpx;background:linear-gradient(135deg,#245f49,#75ad8d);color:#fff;box-shadow:0 18rpx 45rpx #2f805a30}.hero-icon{width:76rpx;height:76rpx;display:flex;align-items:center;justify-content:center;border-radius:24rpx;background:#ffffff20;font-size:47rpx;color:#e4f8ec}.eyebrow{display:block;font-size:16rpx;letter-spacing:3rpx;opacity:.7}.hero-title{display:block;margin-top:8rpx;font-size:30rpx;font-weight:800;line-height:1.35}.hero-desc{display:block;margin-top:8rpx;font-size:19rpx;line-height:1.5;opacity:.84}.card{margin-top:20rpx;padding:26rpx;border-radius:26rpx;background:#fff;box-shadow:0 10rpx 30rpx #2238480b}.card-head{display:flex;justify-content:space-between;align-items:start}.card-title{display:block;font-size:28rpx;font-weight:800}.card-sub{display:block;margin-top:8rpx;color:#9aa59f;font-size:18rpx}.badge{padding:8rpx 14rpx;border-radius:20rpx;background:#e8f7ee;color:#32805d;font-size:16rpx}.status-row{display:flex;align-items:center;gap:16rpx;margin-top:27rpx}.status-icon,.help-icon{width:54rpx;height:54rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#eef7f2;color:#32805d;font-size:30rpx;font-weight:800}.status-title,.help-title{display:block;font-size:22rpx;font-weight:700}.status-desc,.help-desc{display:block;margin-top:7rpx;color:#8d9a93;font-size:18rpx;line-height:1.4}.arrow{margin-left:auto;color:#32805d;font-size:30rpx}.divider{height:1rpx;margin:26rpx 0;background:#edf1ef}.info-grid{display:flex;justify-content:space-between}.info-label{display:block;color:#a0aaa5;font-size:16rpx}.info-value{display:block;margin-top:8rpx;font-size:19rpx;font-weight:700}.help{display:flex;align-items:center;gap:16rpx}.help-icon{background:#fff4e9;color:#c67b34}.primary{height:82rpx;line-height:82rpx;margin-top:28rpx;border:0;border-radius:20rpx;background:#1f7353;color:#fff;font-size:25rpx;font-weight:800;box-shadow:0 12rpx 28rpx #287a5730}.primary text{margin-left:8rpx;color:#d7f6e7}
</style>