package dev.aihub.access;
import org.springframework.boot.SpringApplication; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.*;
@SpringBootApplication public class AccessApplication { public static void main(String[] args){SpringApplication.run(AccessApplication.class,args);} }
@RestController @RequestMapping("/api") class AccessController {
 private final Map<String,Object> metrics=new LinkedHashMap<>(); private final Map<String,List<Map<String,Object>>> data=new LinkedHashMap<>(); private long nextId=1;
 AccessController(){ metrics.put("primary","doors"); metrics.put("title","gate · 门禁安全台"); metrics.put("在线门点","38/40");metrics.put("今日通行","12,864");metrics.put("异常事件","7");metrics.put("访客预约","86"); data.computeIfAbsent("doors",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","研发楼 A 门","detail","人脸 + 刷卡","status","在线","amount","2,486 人")));data.computeIfAbsent("doors",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","园区南门","detail","车牌识别","status","在线","amount","1,208 车次")));data.computeIfAbsent("doors",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"owner","仓储区 2 号门","detail","刷卡","status","告警","amount","86 人")));data.computeIfAbsent("events",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","访客通行","detail","来访：云服务团队","status","已放行","amount","南门")));data.computeIfAbsent("events",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","异常识别","detail","尾随进入提醒","status","待复核","amount","A-1208")));data.computeIfAbsent("events",k->new ArrayList<>()).add(new LinkedHashMap<>(Map.of("id",++nextId,"name","权限变更","detail","员工离职权限回收","status","已完成","amount","3 个门点"))); }
 @GetMapping("/metrics") Map<String,Object> metrics(){return metrics;}
 @GetMapping("/{resource}") List<Map<String,Object>> list(@PathVariable String resource){return List.copyOf(data.getOrDefault(resource,List.of()));}
 @PostMapping("/{resource}") @ResponseStatus(HttpStatus.CREATED) synchronized Map<String,Object> create(@PathVariable String resource,@RequestBody Map<String,Object> body){if(!data.containsKey(resource)) throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND); var item=new LinkedHashMap<String,Object>(body); item.putIfAbsent("id",++nextId); data.get(resource).add(item); return item;}
}